### ISSUE TITLE
Could Sticky be supported?

### ISSUE THREAD

**Issue by liuhuiping2013** [cracker0dks/whiteboard#1]
mouse writing so hard, so sticky will be more usable.
Further more, just support sticky only may be more good for use.

**Comment by poVoq** [comment]
I think he means a small box where you can type in, like a yellow sticky note.

By the way, I just tried this with my Nextcloud15 and besides a small minor issue in relation to the JSXC chat overlay it is working great :)

**Comment by cracker0dks** [comment]
Ah ok thanks. Than my answer is: Yes, could be supported :)
Glad you like it  @poVoq . Im still on NC14 and don't have the JSXC chat so can't help you with that.

**Comment by liuhuiping2013** [comment]
function for type in is very nice for small team

**Comment by cracker0dks** [comment]
added text fields. Not the final form (Have to add some more functions -> undo and stuff) but usable I think :)
PS: You can change the text color with the color picker and the font size with the range slider -> have make it more clear in the future
