### ISSUE TITLE
Provide option to hide menu buttons 

### ISSUE THREAD

**Issue by bpcurse** [cracker0dks/whiteboard#10]
On a small screen the menu buttons can consume quite a lot of space.
This could be mitigated by providing an additional button that hides/collapses the rest of the menu, until needed again, e.g. burger menu:
![Hamburger_icon2 svg](https://user-images.githubusercontent.com/29312856/57315010-fc5f2080-70f2-11e9-9427-bf0cb419f5bd.png)

**Comment by cracker0dks** [comment]
Added https://github.com/cracker0dks/whiteboard/commit/242c62a0cd4dd9a8b4088694d30a46e26b0651fc
cheers

**Comment by bpcurse** [comment]
Works like a charm on desktop and mobile :) Great enhancement in usability on small screens.
Thanks for the efforts!
