### ISSUE TITLE
504 timeout

### ISSUE THREAD

**Issue by utkarshsystem** [cracker0dks/whiteboard#102]
![image](https://user-images.githubusercontent.com/1451615/119712173-547a3400-be2e-11eb-9d7e-df3ca45a64f5.png)

We are sometimes getting 504 timeout while working on whiteboard

**Comment by cracker0dks** [comment]
This seems to be a nginx thing. Maybe try something from here: https://easycloudsupport.zendesk.com/hc/en-us/articles/360002057472-How-to-Fix-504-Gateway-Timeout-using-Nginx
