### ISSUE TITLE
savedboards.json file getting curropted

### ISSUE THREAD

**Issue by sasidatta** [cracker0dks/whiteboard#104]
We have enableFileDatabase to "True" and after running for more than 48 hours, savedboards.json kept exponentially growing up and at some point, savedboards.json file is getting corrupted and size is marked to 0 kb, file is getting empty. This is leading to crash of whiteboard.
-rw-rw-r--   1  29M May 26 00:30 savedBoards.json

**Comment by cracker0dks** [comment]
Please check out the latest version. From now on we create a json file for each board so you might not see this problem with this version.

**Comment by sasidatta** [comment]
Thank you, will try out.
