### ISSUE TITLE
Bug: Unable to undo "Clear whiteboard"

### ISSUE THREAD

**Issue by MaximeKoitsalu** [cracker0dks/whiteboard#115]
Step to reproduce:

1. Draw something.
2. Do CTRL + Shift + Z.
3. Undo change and nothing happens.

This is very annoying since you lose potentially hours of work because a user used CTRL + Shift + Z thinking they would redo a change.

**Comment by cracker0dks** [comment]
At some point we want to get rid of some old data... maybe we should change the binding for clear or add a confirmation for the sortcut?

**Comment by cracker0dks** [comment]
I changed the default binding for "Clear whiteboard" to ctrl+shift+del (Makes more sense anyway)
