### ISSUE TITLE
Minor display issues

### ISSUE THREAD

**Issue by bpcurse** [cracker0dks/whiteboard#12]
The new transparency in the menu buttons has led to a minor display problem concerning the recycle bin. If you click it (and only if you then move the mouse away from it), the checkmark is partially hidden:
![Bildschirmfoto_2019-05-20_15-30-49](https://user-images.githubusercontent.com/29312856/58025276-64aafa80-7b14-11e9-8d31-311a355528e9.png)

Another minor display issue:
The height of the line tool menu button frame seems to be too small:
![Bildschirmfoto_2019-05-20_15-33-50](https://user-images.githubusercontent.com/29312856/58025576-0fbbb400-7b15-11e9-9079-6f5e8a9fe092.png)

Also the height of the line thickness tool seems to be a little bit too small:
![Bildschirmfoto_2019-05-20_15-45-32](https://user-images.githubusercontent.com/29312856/58026281-67a6ea80-7b16-11e9-804b-b439d4ab3946.png)

Sorry for bothering with these trivialities and thank for your work on this great tool!

**Comment by cracker0dks** [comment]
No Problem :) Thanks for reporting. This was a firefox thing so I didn't notice.
Should be fixed with: dda147a5399ebbf0a4555ff4bebdfb9c43b8dd79

**Comment by cracker0dks** [comment]
also saw today that the border from the slider was green the hole time wtf!!! why nobody saw this :D
