### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by nedmhtechnologies** [cracker0dks/whiteboard#123]
Hi, I want to make it responsive, Current branch is not responsive, that can not be used for other devices' screen sizes.
do you have any suggestions about how I can make it responsive so every screen size will have the same preview?

for example, if I draw a square on-screen of 1920x1080 so its preview will have a half square on an 800x400 resolution screen.

Thanks

**Comment by cracker0dks** [comment]
That is not an easy thing to do. I think responsive is not a good solution (You would probably need to define a max X and max Y of the whiteboard and then draw things percentage wise). I think we need something like we discussed here: https://github.com/cracker0dks/whiteboard/issues/21
with maybe an extra minimap. So you would be able to navigate on a big board even on small screens (Maybe with a zoom option).

**Comment by cracker0dks** [comment]
we added a panning tool to the board.
