### ISSUE TITLE
Element / Dimension integration

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#126]
Hi,

I just discovered this Element  [widget](https://github.com/turt2live/matrix-dimension/pull/384) - nice. In the web version everything is fine. On mobile devices, the buttons gets rendered very very large.
![whiteboard_element](https://user-images.githubusercontent.com/47271687/143767509-2481e406-d702-4d73-b7a8-3359ad0d82b5.png)

Do you have any idea how to fix this ?

Regards

edit:
also opened an issue [here](https://github.com/turt2live/matrix-dimension/issues/447)

**Comment by cracker0dks** [comment]
Its hard to find out because I can't reproduce it. Do you have any testserver up?

**Comment by tna76874** [comment]
I deployed dimensions on my matrix server an used the widgets within the dimension integration inside a chat. I'm not familiar how to test the integration itself.

The problem occurs on iOS and Android devices - does that help?

**Comment by cracker0dks** [comment]
not really, on my phone (without matrix integration) I get the correct icon size... so I can't get to the root of this issue :(
