### ISSUE TITLE
Uploaded images not working with NGINX proxy?

### ISSUE THREAD

**Issue by spiral6** [cracker0dks/whiteboard#13]
I think it's attempting to access the uploads folder in the Node app but it's not accessing it correctly?

**Comment by cracker0dks** [comment]
no problem on my end, running always behind a nginx. Maybe you can not upload because of folder permissions?

**Comment by spiral6** [comment]
I'll take a look and confirm it.

**Comment by spiral6** [comment]
Permissions on the folder are fine, but I'm getting this error. 

`Cannot GET /uploads/myNewWhiteboard_1559079930153.png`

**Comment by cracker0dks** [comment]
have you checked that the file exists on the server? I have no clue how to reproduce this

**Comment by spiral6** [comment]
The file does not exist on the server. I guess the file isn't being created/uploaded properly?

**Comment by cracker0dks** [comment]
if file upload fails, you should get an error msg in the server console log.
Should be like this: 
![image](https://user-images.githubusercontent.com/1816621/58748064-cef85f00-8473-11e9-94f9-46f995afc8f5.png)

I also added more error logs to the latest version, maybe we get this problem solved this way

**Comment by spiral6** [comment]
Downloaded and installed the new release. Got this message.

![image](https://user-images.githubusercontent.com/2887489/58753394-138bf680-8484-11e9-8090-f28b0328b878.png)

Same error though.

**Comment by cracker0dks** [comment]
Wut?! Do you upload the img from the harddrive, browser or something else?

**Comment by spiral6** [comment]
I just copied and pasted the image into the whiteboard (on the site). 

Feel free to try it at http://spiral6.xyz/whiteboard

**Comment by spiral6** [comment]
Note that dragging images in does work, as a matter of fact. Just not copy and pasting them.

**Comment by spiral6** [comment]
Here's the relevant location directive in my NGINX configuration.

```
location /whiteboard/ {
        proxy_set_header HOST $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_pass http://192.168.1.104:8080/;
    }
```

**Comment by cracker0dks** [comment]
Config an stuff looks good. I will test the copy+past thing on my installation.

**Comment by spiral6** [comment]
Local installation copy and paste also doesn't work. I just ran it without NGINX, directly from the local IP.

**Comment by cracker0dks** [comment]
but only copy+past ?

**Comment by spiral6** [comment]
Yeah, drag and drop works fine on both local and NGINX proxy.

**Comment by cracker0dks** [comment]
looked into it. The Probelem you might encounter is not really a bug. You can not upload files from the filesystem directly. It works if you open the image in paint or an other image software, then mark and copy it to the whiteboard. If you copy+past from the filesystem you have the file path in the clipboard, not the image data. Browsers don't allow direct file access. 

I added a info modal for that problem to make it clear to the user.

The Problem also explained here: https://stackoverflow.com/questions/45728177/copy-and-paste-file-in-javascript

**Comment by spiral6** [comment]
I wonder how Imgur does it then.

**Comment by spiral6** [comment]
And I wasn't copying and pasting from the filesystem. I was copying and pasting images in my browser using Copy Image.

**Comment by cracker0dks** [comment]
this should work (And is working for me). Can you send me the Image url for testing?

**Comment by spiral6** [comment]
This is the problem with any image, but in this case, I was using my GitHub avatar. 
https://avatars0.githubusercontent.com/u/2887489?s=88&v=4

**Comment by cracker0dks** [comment]
Thanks. Found a bug and I think I fixed it here with this changes a7c02ac47ff2d94e891a2a515155c59d2b9f5aae
In some cases the image url was not detected correct and so the Image url was uploaded as if it was base64.

**Comment by spiral6** [comment]
I tried it again. It did not work. I updated the server to the latest source code that you committed, but no dice. http://spiral6.xyz/whiteboard

**Comment by cracker0dks** [comment]
seems to be a upload problem. The Image data is vaild on client side. On the way to the server something seems to happen to the base64 data. 
You can check out my test Server: http://167.86.87.115:3334/
I cant reproduce it there (and also not an a different server behind a rp), only on your site. I can't debug it deeper on your link as the client side (where everything looks good)

Is this still buggy for you localy? If not, try to test without the reverse proxy once.

**Comment by spiral6** [comment]
Does not work locally, which is without reverse proxy.

**Comment by cracker0dks** [comment]
is it working on my testserver for you?

**Comment by spiral6** [comment]
Yes.

**Comment by spiral6** [comment]
My guess is that it's a permissions issue? Maybe the uploads folder isn't getting written because of permissions?

**Comment by cracker0dks** [comment]
It has to be a problem with your machines. Are you running with docker?

**Comment by cracker0dks** [comment]
maybe run it with sudo for testing, then with docker. I think the problem is a os thing, nothing I can fix on my end...
