### ISSUE TITLE
releases / latest vs dockerhub

### ISSUE THREAD

**Issue by christf** [cracker0dks/whiteboard#130]
Looking at this repository, I can see that the last change was made a few days ago.

Looking at dockerhub, I can see the :latest-Image is from a few months ago.

For me as a user it would be helpful if I could use docker to

* try out the last release (1.6 in this case)
* see if issues that occur also happen in the latest development version which would be :latest

**Comment by cracker0dks** [comment]
You are right, dockerhub changed something so they don't build the images for you anymore. I added a cron to the testserver so it will build and push new versions every night (if necessary). Also pushed the current version a few minutes ago.

**Comment by christf** [comment]
Thank you for your quick response!

I was able to install the most recent version with :latest now.
I would like to use reproducible builds on a fairly new state of the repository. Would you be open to also tagging your commits with the semantic versioning style and add those tags to the images? I am only asking because :latest works really great and includes many bugfixes over :version-1.6
