### ISSUE TITLE
Download whiteboard as image not working

### ISSUE THREAD

**Issue by vmakkadd** [cracker0dks/whiteboard#135]
Hi Team,
I am getting error of 404 for images/ path for https://webhungers-white-board.herokuapp.com/images/
Due to this I am not able to download whiteboard as png file. But in your demo it is working properly.
Please help me how I can resolve it.

**Comment by cracker0dks** [comment]
your server does not allow access to /images. I don't know heroku, but I think you need to change some settings.

**Comment by vmakkadd** [comment]
@cracker0dks Thanks for revert.
