### ISSUE TITLE
Backend Image upload

### ISSUE THREAD

**Issue by xJoffel** [cracker0dks/whiteboard#139]
I messed clearly to long with this one.
The Form Item is only named "wid" so you need to change "whiteboardId" to "wid". Otherwise it returns undefined, which throws no error because undefined itself has a ReadonlyID too.

https://github.com/cracker0dks/whiteboard/blob/cf834d7eb85a7bb46052f3b0464b5b4aea8e229e/scripts/server-backend.js#L215

**Comment by xJoffel** [comment]
similar Problem in this line. "date" needs to be changed to "current".

https://github.com/cracker0dks/whiteboard/blob/cf834d7eb85a7bb46052f3b0464b5b4aea8e229e/scripts/server-backend.js#L220

**Comment by cracker0dks** [comment]
Thanks! Should be fixed now. The second one was wrong in the doc so I changed that there.
