### ISSUE TITLE
esbuild goes zombie on docker container

### ISSUE THREAD

**Issue by diolwe** [cracker0dks/whiteboard#140]
Whiteboard seems to work. But I see Zombies.

Inside of the container:
```
/opt/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 npm run start
   17 root      0:02 node scripts/server.js --mode=production
   30 root      0:00 [esbuild]
   57 root      0:00 /bin/sh
   67 root      0:00 ps aux

```
From Docker Host:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      207849  0.0  0.0      0     0 ?        Z    Feb19   0:00 [esbuild] <defunct>
root     1248992  0.0  0.0   3180   708 pts/0    S+   15:00   0:00 grep Z
```
Seems to happen on Ubuntu 20.04 and Debian 11.
Docker version 20.10.12, build e91ed57
Last docker-compose pull is 4 hours ago.

Any hints about what to do?

**Comment by cracker0dks** [comment]
Don't really know. Seems to be a nodejs problem: https://github.com/evanw/esbuild/issues/1566 don't know why the issue is closed even when not solved. I have the same "problem" on my end: 
![image](https://user-images.githubusercontent.com/1816621/155349030-a4c71bf2-9a5e-4bb1-a59e-655d78d1239b.png)

**Comment by cracker0dks** [comment]
Cant do much on my end because this seems to be a node bug.
