### ISSUE TITLE
[feature request] Pan and Independent pen/eraser sizes

### ISSUE THREAD

**Issue by Lunatunny** [cracker0dks/whiteboard#146]
I wanna start by saying this board is WAY better than most boards out there.

But I can't stand that I'm unable to pan around. I don't mind if it isn't endless or if i can only pan a lil bit. It just gets IMMEDIATELY cramped when more than one person is using it and zooming out to a birds-eye view doesn't help (it's like writing with a pen tied to a stick)

Also, please unlink the eraser size and pen size. It creates the hassle of scribble erasing until you get all of the line so when I draw or write I like it when my eraser is slightly bigger. Since they're linked, I lose my pen size and my lines become inconsistent. I can work around it, but it creates a pretty annoying workflow.

Again, this is a FANTASTIC whiteboard. But these features are a must (mainly the first) before I can continue using it ....

**Comment by cracker0dks** [comment]
yeah, good points, thanks for your feedback! Both points I noticed as well, the second one should be easy to fix, will see if I can do  something about :)

**Comment by Lunatunny** [comment]
Thank you for checking this out and taking the time to reply! This would definitely be one of my favorite docker containers for both me and my friends if you have the time to add these features

**Comment by cracker0dks** [comment]
The current version saves the thickness settings for each tool, please give it a try.

**Comment by matbgn** [comment]
@cracker0dks: For the Pan issue what would be the global approach to fix this programmatically? Is there a plan to add a new "Hand" tool?

**Comment by matbgn** [comment]
Ok duplicate from #21, as the unlinking of pen/eraser is satisfying I propose to close this issue.

**Comment by cracker0dks** [comment]
yep you are right 👍
