### ISSUE TITLE
Difference between with docker and without docker

### ISSUE THREAD

**Issue by wei-jinn** [cracker0dks/whiteboard#15]
Hi cracker0dks, may I know what is the difference of running with docker and running without docker. I tried both ways and I couldn't notice the difference yet. Please kindly guide me. Thanks.

**Comment by cracker0dks** [comment]
there should be none. This is all about how you want deploy applications on your server.
It might be more convenient to use docker if you have a lot of applications run in parallel, but you can use vms or anything you like :)

**Comment by wei-jinn** [comment]
Thanks! Cool whiteboard. Excellent job
