### ISSUE TITLE
Problem to install in server VPS

### ISSUE THREAD

**Issue by Messiaslogia** [cracker0dks/whiteboard#151]
Goog morning.
I'm having trouble installing your software on my VPS server.
Is there a need for any configuration other than those given in the documentation?

ERROR:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start:prod' ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'prestart:prod', 'start:prod', 'poststart:prod' ]
5 info lifecycle whiteboard@1.0.0~prestart:prod: whiteboard@1.0.0
6 info lifecycle whiteboard@1.0.0~start:prod: whiteboard@1.0.0
7 verbose lifecycle whiteboard@1.0.0~start:prod: unsafe-perm in lifecycle true
8 verbose lifecycle whiteboard@1.0.0~start:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/wwshow/crud.showdeimagem.com.br/whiteboard/node_modules/.bin:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin:/opt/cpanel/composer/bin:/home/wwshow/.local/bin:/home/wwshow/bin
9 verbose lifecycle whiteboard@1.0.0~start:prod: CWD: /home/wwshow/crud.showdeimagem.com.br/whiteboard
10 silly lifecycle whiteboard@1.0.0~start:prod: Args: [ '-c', 'npm run build && npm run start' ]
11 silly lifecycle whiteboard@1.0.0~start:prod: Returned: code: 2  signal: null
12 info lifecycle whiteboard@1.0.0~start:prod: Failed to exec start:prod script
13 verbose stack Error: whiteboard@1.0.0 start:prod: `npm run build && npm run start`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid whiteboard@1.0.0
15 verbose cwd /home/wwshow/crud.showdeimagem.com.br/whiteboard
16 verbose Linux 3.10.0-1160.71.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:prod"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error whiteboard@1.0.0 start:prod: `npm run build && npm run start`
22 error Exit status 2
23 error Failed at the whiteboard@1.0.0 start:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by cracker0dks** [comment]
Hey, pls try a newer version of nodejs. Your are using node v12. You should use v16. or newer.
