### ISSUE TITLE
Storing whiteboard data as JSON in database

### ISSUE THREAD

**Issue by wei-jinn** [cracker0dks/whiteboard#16]
Hi cracker0dks.

I like your idea of saving the whiteboard data as JSON. I am trying to post the json data to PHP laravel controller and store it in database(MySQL) via axios http request but I didn't manage to handle it yet. Do you have any suggestion on where I shall start the http post request? In server.js or main.js?

Thanks in advance.

**Comment by cracker0dks** [comment]
Hey, 
on main.js line 157 you have the json string in imgData. You can send a Ajax to your php from there. Probably the best way.
