### ISSUE TITLE
can not open in safari and some mobile browser

### ISSUE THREAD

**Issue by andeyeluguo** [cracker0dks/whiteboard#162]
when open it， it is blank.
https://cloud13.de/testwhiteboard/

**Comment by cracker0dks** [comment]
do you get any error in the browser console? F12 -> Console ? 
Thanks

**Comment by pno-limtec** [comment]
it seems, that pdfjs-dist is incompatible with safari, because safari doesn't support the private class fields ES2022 feature
i managed to get it work with an older version of pdfjs-dist. use npm install pdfjs-dist@v2.4.456

**Comment by cracker0dks** [comment]
mmm I think we should not deliver with an old version of that lib
