### ISSUE TITLE
Get ink information

### ISSUE THREAD

**Issue by nunores** [cracker0dks/whiteboard#163]
Hi! Is there any way that I can obtain the information of the handwritten strokes?

Ultimately I would like to extract the strokes of the drawn data present on the whiteboard (drawn by anyone) in order to export them into a file type like InkML.
I would kindly appreciate some insight on where I could find this data stored internally.

InkML files look like this: [exp.txt](https://github.com/cracker0dks/whiteboard/files/10812995/exp.txt)

**Comment by cracker0dks** [comment]
Hey, I dont know the inkML format this should do the trick: just save (export) the whiteboard as JSON

![image](https://user-images.githubusercontent.com/1816621/220906992-609e9390-fc51-4cf5-a46f-747d3dd5e7c9.png)

then take a look inside the file. You will see every stroke like this:

![image](https://user-images.githubusercontent.com/1816621/220906545-33847bf5-73ac-4375-895a-050ac52ca6a3.png)

you would need to read in the JSON file and convert just the pen strokes to your format. 
good  luck :)

**Comment by nunores** [comment]
I see! I saw that you have undo/redo features and from what I understand you are grouping these mini-strokes into bigger strokes through interpolation, and these are the ones deleted when undoing. Are these groups stored anywhere?

**Comment by cracker0dks** [comment]
It is only grouped from mouse down to mouse up. What you see in the screenshot above is already a "grouped stroke". We dont have "mini-strokes".
The interpolation is only done inside one stroke to make it smooth :)
