### ISSUE TITLE
Problem with stylus (drawing small things)

### ISSUE THREAD

**Issue by Krzysztof-Dziardziel** [cracker0dks/whiteboard#17]
Hello,
I'm having issues drawing small things with a stylus. The drawing doesn't follow the path of the tool.

Please help me in finding what the issue might be.

![image](https://user-images.githubusercontent.com/56971803/74758979-6149c880-5278-11ea-9699-f65463adca9d.png)

**Comment by cracker0dks** [comment]
can you sen me the image with the grid in the background so I get a feeling of how small this is?
Do you draw with mouse or with touchscreen with finger or pen?

**Comment by Krzysztof-Dziardziel** [comment]
I'm drawing with a pen - 6b4d31f didn't help.
![image](https://user-images.githubusercontent.com/56971803/74762612-7c1f3b80-527e-11ea-905d-acff46b73f01.png)

**Comment by cracker0dks** [comment]
Ok, found some bugs for events, not sure if it is fixing your problem. I only could test touch (with finger) on mobile Android Chrome/Firefox. fix https://github.com/cracker0dks/whiteboard/commit/5dca96cbd301e11a9a9982cd727a9151cdc47d2d
On what device and with what Browser are you testing?

**Comment by Krzysztof-Dziardziel** [comment]
Problem persists.
Surface Pro 7 with Surface Pen
Chrome 80.0.3987.116x64 & Opera 66.0.3515.103x64
It seemed like a chromium-related problem so I checked Brave 1.3.118. Same thing.

Firefox works just fine.

**Comment by cracker0dks** [comment]
I dont have a Sufrace so I can't really reproduce. Are you able to check the console and check for some erros?

**Comment by Krzysztof-Dziardziel** [comment]
I don't get any logs apart of 'Websocket connected!'.
I think it is some kind of problem with beginning a line. If I try to draw a straight line and then continue that one, I'm easily able to draw "2".
![image](https://user-images.githubusercontent.com/56971803/74977339-d0ffb500-542a-11ea-8124-fafc7d9e7422.png)

**Comment by cracker0dks** [comment]
seems to be a surface problem? Check out this post: https://groups.google.com/a/chromium.org/d/msg/chromium-discuss/43EvDVGan6E/MExSvi3FAgAJ
Maybe this helps

**Comment by cracker0dks** [comment]
we changed how we draw on the canvas so please reopen if you have more infos or still encounter this problem.
