### ISSUE TITLE
please cancel my commit change by mistake.

### ISSUE THREAD

**Issue by jmc-123** [cracker0dks/whiteboard#171]
when try to deploy on vercel and failed ,encountering 

#Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
#STATIC_BUILD_NO_OUT_DIR: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
-----
modify the package.json by mistake, please cancel my commit change ,Thanks.

**Comment by cracker0dks** [comment]
If I understand it correctly, this can be closed then? I will reopen if you say so :)
