### ISSUE TITLE
Is this legit?

### ISSUE THREAD

**Issue by zeritonius** [cracker0dks/whiteboard#176]
I'm not sure how to ask this the right way. With all due respect, and without any intention to offend or to be ironic, is this software legit?

I'm asking because of the word "cracker" from cracker0dks (the name of the owner of this repository).

The software is excellent and it worked as described, from the first try. I just want to make sure it's okay to use it in production.

Thank you.

**Comment by cracker0dks** [comment]
sry for the late reply. Yeah its legit. The word "cracker" should mean nothing besides the german word for something like a cookie ;)
