### ISSUE TITLE
Doesn't run on ec2 instance

### ISSUE THREAD

**Issue by najeeb-ur-rahaman** [cracker0dks/whiteboard#182]
Hi
I cloned the code into an amazon ec2 instance and followed the steps you mentioned. After running the command " npm run start:dev" when i go to the url the url doesn't show me anything. Did i do something worng. Can you please help.

**Comment by cracker0dks** [comment]
Please post the console output / error msgs you get?

**Comment by najeeb-ur-rahaman** [comment]
I am running the code on an ec2 instance. so i need to modify the code to connect to the instance ip address. But i am not sure where to do it

![image](https://github.com/cracker0dks/whiteboard/assets/67108868/07eaa940-e0da-469d-8664-13f3195e8937)
The applications running but i cant see the output

**Comment by cracker0dks** [comment]
I think this is not a problem related to this whiteboard sry for the late reply. You need to know your public IP and add the correct port to connect to the application ( IP:8080 )
