### ISSUE TITLE
WhiteboardAPI | Draw on the Whiteboard

### ISSUE THREAD

**Issue by khoo2002** [cracker0dks/whiteboard#185]
http://localhost:3000/api/drawToWhiteboard/?wid=hi&query=[%20{%20%22t%22:%20%22circle%22,%20%22d%22:%20[%20698,%20391,%20272.4646766096479%20],%20%22c%22:%20%22rgba(0,0,0,1)%22,%20%22th%22:%204,%20%22at%22:%20%22%22%20}%20]

![image](https://github.com/cracker0dks/whiteboard/assets/50482835/e3c0bafb-1cbd-4ca4-a523-f42836d53162)

No circle is loading.

**Comment by khoo2002** [comment]
@lightswitch05 @Manawyrm @maltsev @pkschweiger Please help me😭 My assignment almost due.

**Comment by cracker0dks** [comment]
sorry for the late respons. Please pull the latest code and try local: http://127.0.0.1:3000/api/drawToWhiteboard?wid=myNewWhiteboard&t=circle&d=[388,201,100]&th=4
