### ISSUE TITLE
Feature Request: Video and images as object support

### ISSUE THREAD

**Issue by DingosGotMyBaby** [cracker0dks/whiteboard#193]
Hi there, great project you have here

Just wondering if there will be any support for videos and images as individual objects (i.e. you can put an image/gif/mp4 into the board and then drag it wherever on the board) coming in the future. 

We are want to be able to use this for planning things and having to draw the image to the canvas then not be able to move it afterwards is a bit painful.

Thank you in advance

**Comment by cracker0dks** [comment]
Hey,
sorry, not plans to support that. You can cut out and move images if you draw them to the canvas. Moving them in the background is not supported right now (but would be possible to implement if you want to? :D ).
