### ISSUE TITLE
Cyrillic character support

### ISSUE THREAD

**Issue by semencha** [cracker0dks/whiteboard#20]
Hello!

Thank you for a good project, if possible, add support for fonts with critical symbols, as well as information about the user of the board in UTF-8

Thanks.

**Comment by cracker0dks** [comment]
Thanks should be fixed now: https://github.com/cracker0dks/whiteboard/commit/62c77dac835a04cd9dab82c79172a98210811ccb

**Comment by semencha** [comment]
Hello!

Thank you very much for the operational changes, unfortunately they did not help in solving the problem, so I ask you to do:

1. When displaying the username on the board, please do it through the conversion encodeURI (username) (username is the parameter passed in the url request). This will display Cyrillic characters and spaces in the username;
2. When zooming the board, also zoom in on the username displayed on the board and the toolbar;
3. Please use a font that contains Cyrillic characters, now if you use the “Text” element and try to enter the sentence “Из России с любовью!” other participants will not see this text.

With respect and gratitude, 
Ivan Semencha
