### ISSUE TITLE
Endless board

### ISSUE THREAD

**Issue by semencha** [cracker0dks/whiteboard#21]
Hi!

Are you planning to realize the possibility of an endless board and the ability to navigate on it?

It would also be interesting to see which particular user edited what part of the information on the board.

Thank you for your work.

**Comment by cracker0dks** [comment]
Sry, no plans for both of them atm. But I like the idea of an endless board :)

**Comment by bpcurse** [comment]
Somehow related:
If a user with a larger screen draws anything outside the screen limits of another user, there doesn't seem to be a browser overflow handling by scrollbars (tested on Firefox).

**Comment by cracker0dks** [comment]
@bpcurse  I don't like the idea of scrollbars especially on mobile devices. Is this a real problem you encounter? If so, we might find an other better solution than scrollbars.

**Comment by bpcurse** [comment]
Continuing at #22

**Comment by semencha** [comment]
Hi!
To navigate the board, you can use a group of buttons, increase, decrease, left, right, top, down (select them either in the existing toolbar or in a separate navigation panel, like on the remote control).

**Comment by cracker0dks** [comment]
zoom is not really possible without firefox supporting zoom (https://github.com/cracker0dks/whiteboard/issues/22#issuecomment-601385018) if we transform every element on its own we might have a different view on different clients. Not a proper solution.
The "endless" board however is still an option, I would navigate it with a tool looking like this: 
![grafik](https://user-images.githubusercontent.com/1816621/77189432-d575c700-6ad7-11ea-8850-851e61e4bf17.png)
but moving the canvas... however, I don't think I have the time to implement this in the near future

**Comment by semencha** [comment]
You're right the navigation bar will be enough.

**Comment by matbgn** [comment]
To avoid cross issue I repeat myself here:

What would be the solution to move the canvas' view with a custom tool, as far as your research moved you forward?

**Comment by cracker0dks** [comment]
Pan Solution I have in mind: For drawings on the canvas we just need to remember our current view point and draw all the things on the canvas with an offset defined by the user pan. We need to update the view point and redraw the canvas every time a user used the pan tool. 
The background images / text fields / notes and stuff... position would also depend on the view point (and also would need an update every time)

**Comment by matbgn** [comment]
Thanks!

Any plan in months/years you'll dedicate some time on it?

**Comment by cracker0dks** [comment]
sry can't give you a timespan. Would like to have it as well but its not really a game breaker (And more work than it seems) so... not on my top 10 list of things to do atm.

**Comment by matbgn** [comment]
Ok I understand, even if with pan/infinite board feature you will either significantly improve, workaround or resolve all those issues #22, #43, #61, #75 and #123. Quiet some impact nop?

Would you maybe be available for a quick peer programming session of no more than 1h maybe? A take off session would I say.

**Comment by matbgn** [comment]
Moreover it looks like, at the moment, it's the most discussed open issue of this project even before I touched it today.

**Comment by cracker0dks** [comment]
You are right, would solve/improve a lot, maybe I need to put it in top 10 :D
Lets discuss the peer programming thing via mail: [raphael@cloud13.de](mailto:raphael@cloud13.de)

**Comment by matbgn** [comment]
Email just sent right now :wink:

**Comment by matbgn** [comment]
Just for you folks :smile::
![Image not loaded](https://s4.ezgif.com/save/ezgif-4-dc4e56c098.gif)


@cracker0dks did an amazing job so far!!! Need some fix but seems that we are on track.

**Comment by matbgn** [comment]
@cracker0dks did an amazing job as always! The branch matbgn-endlessBoard is almost ready and a merge in master will be released soon :wink:

**Comment by cracker0dks** [comment]
and also a huge thanks to you @matbgn for always keeping me motivated and getting me on the right tack 👍 
was fun! 
Im looking forward to close all those open issues  :P

**Comment by cracker0dks** [comment]
Thanks again to @matbgn, we finally have it implemented 👍
