### ISSUE TITLE
How to manage content outside the screen boundaries

### ISSUE THREAD

**Issue by bpcurse** [cracker0dks/whiteboard#22]
### Continuing the discussion from #21

> @bpcurse I don't like the idea of scrollbars especially on mobile devices. Is this a real problem you encounter? If so, we might find an other better solution than scrollbars.

I agree that scrollbars on mobile aren't pretty :smile: 
In this case the issue is the desktop device's display.

Desktop:
![Bildschirmfoto_2020-03-19_18-09-51](https://user-images.githubusercontent.com/29312856/77095394-1d301c00-6a0e-11ea-84f1-ad26d7eae7c5.png)

Mobile:
![Screenshot_20200319-181326](https://user-images.githubusercontent.com/29312856/77095430-2ae5a180-6a0e-11ea-8d89-8f809e84a239.png)

You did a great job for mobile as it seems to automatically adapt the zoom factor :+1: 

I'm not sure what alternative solution (to scrollbars) is possible on a desktop, but I'm not experienced in these things. BTW we are using the newest version you just released.

**Comment by bpcurse** [comment]
What I intuitively tried on the desktop device was to use the mouse scroll wheel.
Maybe the scroll wheel could zoom?

**Comment by cracker0dks** [comment]
I looked into it and sadly you can't change the browser zoomlevel on firefox with javascript: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom and css transform is also not working as expected (Whiteboard is smaller but also moves to the middle of the screen)


But in all browsers you can zoom by pressing Ctrl+Mousewheelscroll... so I've tested this and fixed some bugs on that part: https://github.com/cracker0dks/whiteboard/commit/bc9f97b8da403ca6379e4302b92d8921d825bfcc
So this should be at least give a workaround for browsers.

**Comment by christf** [comment]
zooming is great to get an infinite whiteboard however it mey lead to the content being too small.
So to make an infinite whiteboard usable, a panning feature is required.

**Comment by cracker0dks** [comment]
we added a panning tool to the board.
