### ISSUE TITLE
Cyrillic charset support

### ISSUE THREAD

**Issue by semencha** [cracker0dks/whiteboard#23]
Hello!

Thank you very much for the operational changes, unfortunately they did not help in solving the problem, so I ask you to do:

1. When displaying the username on the board, please do it through the transformation encodeURI(username), username is the parameter passed in the url request. This will display Cyrillic characters and spaces in the username;
2. When zooming the board, also zoom in on the username displayed on the board and the toolbar;
3. Please use a font that contains Cyrillic characters, now if you use the “Text” element and try to enter the sentence “Из России с любовью!” other participants will not see this text.

With respect and gratitude, 
Ivan Semencha

_Originally posted by @semencha in https://github.com/cracker0dks/whiteboard/issues/20#issuecomment-601608242_

**Comment by cracker0dks** [comment]
Username and text issue should be fixed with: https://github.com/cracker0dks/whiteboard/commit/9eebdeeddd6d8119410abf158f6796781516cca3 

I dont really under stand your 2. point. I can't control if you zoom your browser window (we have no other zoom implemented yet)

**Comment by semencha** [comment]
Thank you very much, the problem has been completely resolved. 

About zooming, I realized that there would be enough navigation buttons.
