### ISSUE TITLE
Whiteboard shortcut keys

### ISSUE THREAD

**Issue by semencha** [cracker0dks/whiteboard#25]
Hello!

It is more comfortable to work on the whiteboard using interactive displays, such as Xp-pen Artist, Huion Kamvas and Wacom Cintiq, such devices have quick buttons (6-8 buttons and scroll). By default, the buttons on these displays are mapped to standard Photoshop keyboard shortcuts. Keys can becustomized to function efficiently in other software.

Please add the ability to access the toolbar items using shortcut keys, as well as the ability to configure a combination of keys and apply these settings when starting the server.

Next, I suggest default values ​​for various controls:

- Clear the whiteboard - Ctrl+Shft+Z
- Undo your last step - Ctrl+Z
- Take the mouse - Esc
- Select an area - Ctrl+A
- Take the pen - Ctrl+P
- Take the eraser - Ctrl+E
- Toggle Pen/Eraser - Ctrl+B
- Draw a line - Ctrl+L
- Draw a rectangle - Ctrl+R
- Draw a circle - Ctrl+C
- Switch Line/Rectangle/Circle - Ctrl+D
- Write a text - Ctrl+T
- Thickness decrease size - Shft+[
- Thickness increase size - Shft+]
- Colorpicker - Shft+Z
- Predefined color shortcut keys
  - Black - Shft+0
  - Blue - Shft+1
  - Green - Shft+2
  - Red - Shft+3
  - Yellow - Shft+4
- Save whiteboard as image - Ctrl+S
- Save whiteboard as JSON - Ctrl+[
- Save whiteboard to webdav - Ctrl+W
- Upload image to whiteboard - Ctrl+U
- Load saved JSON to whiteboard - Ctrl+]
- Share whiteboard - Shft+S
- Show / Hide buttons - Tab
- Move selected item Up/Down/Left/Right - Up/Down/Left/Right
- Move whiteboard - Shft+Up/Down/Left/Right

Also need a button on the toolbar button, when clicked, a dialog box appears with a description of the shortcuts keys.

Regards to you and the project
Ivan Semencha

**Comment by cracker0dks** [comment]
Added a shortcut function: https://github.com/cracker0dks/whiteboard/commit/bdff756704a1ed4beca31452617f0be0d5fcaa31

Take a look at [/public/js/keybinds.js](https://github.com/cracker0dks/whiteboard/blob/master/public/js/keybinds.js) to see the default bindings.

I had to change some because for example: strg+t always opens a new tab so we cant use it and so on... but you can rebind them to your needs. 

Move whiteboard is missing because we have no function to move the board atm.

What is still missing:
* Button to show the bindings to the user (maybe a rebind for the user)
* A nice way to change the bindings if running inside docker
* Documentation

greetings :)

**Comment by semencha** [comment]
Hello!

I am very grateful to you for responding.

I tested the changes, my comments:
- saveWhiteboardAsJson saves a picture, not JSON
- Due to the fact that the ctrl-d combination in Firefox is a bookmark saving, it is better to switch switchLineRecCircle to shift-f
- Due to the fact that, by default, the ctrl-w combination closes the active window, so uploadWhiteboardToWebDav is better to shift to shift-w
- moveDraggable Up/Down/Right always moves only the first text element, I suggest moving the last added element or the current selected object (if possible).
- Please add switch Pen/Eraser, shift-p combination
- Please add the color switch Black/Blue/Green/Yellow/Red, shift-r combination

I agree with you that redefining hotkeys by users is a good idea.

Thanks :)

Respectfully,
Ivan Semencha

**Comment by cracker0dks** [comment]
your comments should be fixed with: https://github.com/cracker0dks/whiteboard/commit/31b952fa0936cbcc3cf197d441adb01a331ff8e5
I also added shift+enter to add images to the background and renamed "switch" to "toggle".

Still missing: 

*    Button to show the bindings to the user (maybe a rebind for the user)
*    A nice way to change the bindings if running inside docker
*    Documentation

**Comment by semencha** [comment]
Thank you, everything is great!
Need my help preparing documentation?

Respectfully,
Ivan Semencha

**Comment by cracker0dks** [comment]
Thanks for your offer. If you want you can create a section for shortcuts explaining the current default bindings. That would be nice :)
I don't think we need a translation atm (do you think so?), also it needs to stay up to date and thats the problem on the long run.
greetings

**Comment by cracker0dks** [comment]
had to change the bindings because of: https://github.com/cracker0dks/whiteboard/issues/26

**Comment by semencha** [comment]
Hi!

Perfect solution. I take the section for explaining shortcuts to work.

**Comment by semencha** [comment]
Re-checked all combinations again:
- In Firefox, the combination **defmod-shift-p** (togglePenEraser) launches a private view window, I suggest using **defmod-shift-x**
- The combination **defmod-shift-0** (setDrawColorBlack) does not work on Windows, I suggest using **defmod-shift-5**
- The combination **defmod-shift-s** (saveWhiteboardAsImage / shareWhiteboard) has been duplicated, for saveWhiteboardAsImage I suggest using **defmod-\\**
- The combination **defmod-shift-w** (uploadWhiteboardToWebDav) closes the current window, I suggest using **defmod-shift-\\**
- The combination **defmod-shift-j** (saveWhiteboardAsJson / uploadJsonToWhiteboard) is duplicated:
  - for saveWhiteboardAsJson I suggest using **defmod-[**
  - for uploadJsonToWhiteboard I suggest using **defmod-]**

I checked the proposed combinations in two Firefox Chrome browsers.

Sincerely, Ivan Semencha

**Comment by cracker0dks** [comment]
Done with: https://github.com/cracker0dks/whiteboard/commit/3dfb641be8577a761304a88d3be7113799e20778
I've also tested with chrome/firefox. The problem with keys like "\" and "[" is the keyboard layout... not a vaild option for german layouts "[" fe. is already a combination here so we can't use it. 
Greetings

**Comment by semencha** [comment]
Hello!

Text prepared.

Sincerely, Ivan Semencha

---
### Default keyboard shortcuts

Use keyboard shortcuts to become more productive while using Whiteboard.

They are especially useful if you work with interactive displays such as XP-PEN Artist, Huion Kamvas and Wacom Cintiq. These devices have quick buttons (6-8 buttons and scrolling). By default, the buttons on these displays are mapped to standard Photoshop keyboard shortcuts. Keys can be configured to function effectively in other software.

The following are predefined shortcuts that you can override in file the [/public/js/keybinds.js](https://github.com/cracker0dks/whiteboard/blob/master/public/js/keybinds.js)

Result | Windows and Linux | macOS
-------- | -------------------------- | ----------
Clear the whiteboard | Ctrl + Shift + Z | Command + Shift + Z
Undo your last step | Ctrl + Z | Command + Z
Select an area | Ctrl + X | Command + X
Take the mouse | Ctrl + M | Command + M
Take the pen | Ctrl + P | Command + P
Draw a line | Ctrl + L | Command + L
Draw a rectangle | Ctrl + R | Command + R
Draw a circle | Ctrl + C | Command + C
Toggle between line, rectangle и circle | Ctrl + Shift + F | Command + Shift + F
Toggle between pen and eraser | Ctrl + Shift + X | Command + Shift + X
Toggle between main clolors (black, blue, green, yellow, red | Ctrl + Shift + R | Command + Shift + R
Write text | Ctrl + A | Command + A
Take the eraser | Ctrl + E | Command + E
Increase thickness | Ctrl + Up Arrow | Command + Up Arrow
Decrease thickness | Ctrl + Down Arrow | Command + Down Arrow
Colorpicker | Ctrl + Shift + C | Command + Shift + C
Set black color | Ctrl + Shift + 1 | Command + Shift + 1
Set blue color | Ctrl + Shift + 2 | Command + Shift + 2
Set green color | Ctrl + Shift + 3 | Command + Shift + 3
Set yellow color | Ctrl + Shift + 4 | Command + Shift + 4
Set red color | Ctrl + Shift + 5 | Command + Shift + 5
Save whiteboard as image | Ctrl + S | Command + S
Save whiteboard as JSON | Ctrl + Shift + K | Command + Shift + K
Save whiteboard to WebDav | Ctrl + Shift + I (i) | Command + Shift + I (i)
Load saved JSON to whiteboard | Ctrl + Shift + J | Command + Shift + J
Share whiteboard | Ctrl + Shift + S | Command + Shift + S
Hide or show toolbar | Tab | Tab
Move selected object up | Up Arrow | Up Arrow
Move selected object down | Down Arrow | Down Arrow
Move selected object left | Left Arrow | Left Arrow
Move selected object right | Right Arrow | Right Arrow
Drop object | Ctrl + Enter | Command + Enter
Add Image to backgroud | Shift + Enter | Shift + Enter
Cancel all actions | Escape | Escape
Delete selected object | Delete | Delete

**Comment by cracker0dks** [comment]
Thanks a lot!
Greetings

**Comment by cracker0dks** [comment]
I think I want to keep it simple for now and don't add an extra option to dynamic rebind. If someone really needs this he can change the keybind.js
