### ISSUE TITLE
Whiteboard shortcut keys Problem

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#26]
When opend a Text-Field the shortcuts are resulting in total chaos because text color is changing, etc ... 

but keep up the good work - you are a hero in these days!

**Comment by cracker0dks** [comment]
thanks for your post, you mean you are able to change the text color with shortcuts? thats a feature not a bug :D
you can change text color, size, move it... (even with shortcuts) that is indeed intended.

**Comment by tna76874** [comment]
Yeah I know - but if you want to write capital letters in the text field, the text keeps chaning colors (for example). Because the shortcut is shift+...

:)

would it be possible to possible to change the shortcur for strg+shift+.... or only strg+ ?

Regards

**Comment by bpcurse** [comment]
+1 for ctrl+shift

**Comment by cracker0dks** [comment]
should be fixed with: https://github.com/cracker0dks/whiteboard/commit/fe77e813e17bcc086c17bd942c219abda60c3c48

**Comment by semencha** [comment]
Friends, 

I apologize for the difficulties you have in working, because I did not think about capital letters when I made a proposal to add shortcurt functions.

Sincerely, Ivan Semencha

**Comment by tna76874** [comment]
Thank you very much buddy ! I really mean it - people like you are the real heros now. Offering self hosted and independent open source solutions give very much stability. Keep up the good work!

**Comment by cracker0dks** [comment]
@tna76874 thanks for your kind words :)

**Comment by tna76874** [comment]
sorry buddy that I pop up here again. Apparently there is another issue with the textfield. Is it just me or does creating a new line via enter work no more?

**Comment by cracker0dks** [comment]
no problem, thanks for the report. Should be fixed now: https://github.com/cracker0dks/whiteboard/commit/d21953ede1535107a263cadbfa3e8a0d2790fcdc
greetings

**Comment by tna76874** [comment]
Thanks buddy - seems fine now :)
