### ISSUE TITLE
Whiteboard-name in tab title

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#27]
If you have multiple whiteboards open for several groups of people you have to coach, it would be extremely handy to have a way to (human-readable) distinguish between the tabs.

How about to add the possibility to append a tab name via 

&tabname=group1

Regards :)

BTW: there is a double definition
'defmod-shift-j' : 'saveWhiteboardAsJson',
'defmod-shift-j' : 'uploadJsonToWhiteboard',

**Comment by semencha** [comment]
There is already a whiteboardid parameter in the URL, it can be used in the name of the tab.

About redefinition already considered https://github.com/cracker0dks/whiteboard/issues/25

Sincerely, Ivan Semencha

**Comment by cracker0dks** [comment]
@tna76874 yes this is already working, just change the whiteboardid to a different one and you are drawing on a different board: [howTo](https://github.com/cracker0dks/whiteboard#url-parameters)
@semencha Should be working now with all the characters as whiteboardid : https://github.com/cracker0dks/whiteboard/commit/31351ea2e27e390f8daecb9d6a38a1401c96547f
greetings
