### ISSUE TITLE
Read only link

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#28]
It would be fantastic to have a **read-only** link of an actual whiteboard! (similar to etherpad)

:)

**Comment by semencha** [comment]
I propose to look at the task wider.

In distance learning scenarios, the management functions of participants are very much in demand.

When a teacher sees a list of all participants who have now opened the same whiteboard, with the opportunity for the teacher to provide the whiteboard in read-only mode or to enable one, several or all participants to work together on the whiteboard.

Very grateful!

Sincerely, Ivan Semencha

**Comment by tna76874** [comment]
hi buddys,
thanks for you work in the last weeks - we appreciate it!

Would it be possible to integrate a very basic and simple method to share a write only link? maybe by hashing the ID?

Regards

**Comment by cracker0dks** [comment]
This feature is already on a fork I saw. I think will get this implemented/merged anytime soon.

**Comment by tna76874** [comment]
cool! Now I'm very curious :) Thank you!

**Comment by tna76874** [comment]
First of all - THANKS for the PR - awesome

https://github.com/cracker0dks/whiteboard/pull/50

I think it would be good to get an read-only link if pressing the "Share-Link-button"  while the lock is enabled. Is this a big deal to implement?

**Comment by FloChehab** [comment]
Hi @tna76874,

I am finishing another PR. I'll tackle the read-only link after that. It's only a few lines of code away (not a big deal to implement).

**Comment by tna76874** [comment]
hi,
something new here?

**Comment by FloChehab** [comment]
> hi,
> something new here?

Hi,
It's still a WIP, I have a bit less free time theses days, but I'll try to finish it on Monday :)

**Comment by tna76874** [comment]
> Hi,
> It's still a WIP, I have a bit less free time theses days, but I'll try to finish it on Monday :)

Thank you very much :) We are always looking forward for new features and appreciate you work very much :)

**Comment by FloChehab** [comment]
Hi @tna76874,
The PR (https://github.com/cracker0dks/whiteboard/pull/59) is live :)

**Comment by tna76874** [comment]
> Hi @tna76874,
> The PR (#59) is live :)

cool thanks - lets to a bit of testing in the next time. I'll report if I recognize something strange :)
