### ISSUE TITLE
Add optionally random whiteboardid if empty

### ISSUE THREAD

**Issue by uzsolt** [cracker0dks/whiteboard#31]
Thanks for your work I'm using it with my students.
Would be great if open with empty "whiteboardid" then whiteboard generates a random ID (optionally).

**Comment by cracker0dks** [comment]
great idea, added with this: https://github.com/cracker0dks/whiteboard/commit/c0ae6031d5c94d78674b030d7c07de30e31f1e75
if you set "randomid" to "true" (as get parameter), like this:
`myWhiteboard.com?randomid=true`
 a random whiteboardId will be set for you.
greetings

**Comment by uzsolt** [comment]
Thanks!
