### ISSUE TITLE
Shortcut conflcts

### ISSUE THREAD

**Issue by jb-leger** [cracker0dks/whiteboard#37]
I introduce a redo function, but I choose `ctrl-shift-z` because `ctrl-x` was already used. But I forget that `ctrl-shift-z` was already used for clean the bord.

I do not see trivial solution, a a choice must be done, so I do not propose a PR, but I open a issue.

It is your choice, but some options are (this list is not limitative):

 - put redo in `ctrl-x`, and rect-select in another key, to have the undo/redo like many other apps,
 - find another shortcut for redo,
 - keep redo in `ctrl-shift-z` and find another key for clear the board.

**Comment by cracker0dks** [comment]
Hey, I changed redoStep to "defmod-y" for now. What do you think? Do you/anybody see any problems with this?

**Comment by jb-leger** [comment]
That's good for me. Do not forget the `README` (it is where I see my mistake). Thanks.

**Comment by cracker0dks** [comment]
done, thanks!
