### ISSUE TITLE
Provide service only if a valid token was submitted

### ISSUE THREAD

**Issue by bpcurse** [cracker0dks/whiteboard#4]
It seems that the server provides service to everyone who knows the uri. If you know/guess the BoardID you can even watch the boards.
As a security measure I would suggest that the server only provides service if a predefined general access token is submitted.
An additional enhancement could be board associated keys/tokens.

**Comment by Tmktahu** [comment]
I feel like those kinds of security measures would be handled by whatever API server is built alongside the whiteboard. How a user wants security configured will change from environment to environment, so keeping the whiteboard functionality to just the whiteboard itself may be smarter.

In addition, I'm pretty sure the changes you're suggesting would be handled outside of the whiteboard logic itself. The developer may want to keep this project centered around the whiteboard functionality and not other aspects of server implementation.

**Comment by bpcurse** [comment]
In the use case of a simple nextcloud integration via external sites app at least a general access token check seems to be necessary and probably not too much effort to implement.

**Comment by cracker0dks** [comment]
hey, why are you not define a random boardname (id)?
https://YOURIP/whiteboard/?whiteboardid=myWB1_R72kdgBqP397Bs&username={uid}

I see no downside, and no one will guess it. Do I miss something?

**Comment by bpcurse** [comment]
> An additional enhancement could be board associated keys/tokens.
Yes you are right, it solves the above point.

But doesn't it still open up the server for use by everyone who knows the base uri?

Really great piece of software, by the way!

**Comment by cracker0dks** [comment]
thanks :)
yeah for that purpose I think I will implement a access token you can set on the server side, if you want to activate the feature. (also as Docker env variable)

I thought you meant each whiteboard has its own access token

**Comment by cracker0dks** [comment]
Done, take a look here on how to setup: https://github.com/cracker0dks/whiteboard/blob/master/README.md#security---accesstoken-optional

**Comment by bpcurse** [comment]
Wow, thank you for the fast implementation and documentation of this feature!

May I suppose a change in the label of the provided nextcloud icons?
The file "whiteboard-new.png" should be labeled "whiteboard-dark.png" to meet nextcloud standards. This way it will be automatically detected after upload as a pair and used accordingly in the different themes.

**Comment by cracker0dks** [comment]
No Problem :) also changed the filename! thanks for that hint.
