### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#40]
Can you please add simple docker-compose.yml file that implements the environment variables.

Thanks :)

eg.:
version: '3.1'
services:
  whiteboard:
    image: rofl256/whiteboard
    restart: always
    ports:
      - 8080:8080/tcp
    environment:
      - ACCESSTOKEN:mysecrettoken

**Comment by cracker0dks** [comment]
sure, done :)

**Comment by tna76874** [comment]
Can you please check, if the environment variable ist handed to the java script? Is it just me, or it the accesstoken not working?

**Comment by tna76874** [comment]
I got it working: must be

- accesstoken=mysecrettoken

**Comment by cracker0dks** [comment]
ty is fixed
