### ISSUE TITLE
On mobiles (ios): Buttons hidden, unable to change zoom and view-area

### ISSUE THREAD

**Issue by dwarfi09** [cracker0dks/whiteboard#43]
I stumble across a problem with different users' screen-sizes during collaborations. The view-area and zoom on mobiles (iOS both with safari and chrome) changes "magically". This leads into situations where you can't see the buttons anymore:

![wb](https://user-images.githubusercontent.com/11966701/80291431-cffe4300-874d-11ea-92fd-9cf9b762282a.png)

It's not possible to change the zoom or move the view-area on the mobile, because the gestures are catched by the whiteboad and this just results into funny drawings...

It would be so great if
1. the user could disable auto-zooming / auto-moving
2. the user could choose whether the gestures should draw into the canvas (like it is now) or zooms / moves / scrolls (as he is used to). Something like a button "release mouse".

**Comment by cracker0dks** [comment]
not as easy as it sounds. maybe we could detect the zoom gesture. Maybe also related to: https://github.com/cracker0dks/whiteboard/issues/21 and https://github.com/cracker0dks/whiteboard/issues/22

**Comment by kkneutgen** [comment]
Yes, a navigation as discussed in #21 in combination with zoom-buttons should also work.

**Comment by cracker0dks** [comment]
we added a panning tool to the board.
