### ISSUE TITLE
Embedding PDF as images

### ISSUE THREAD

**Issue by yrammos** [cracker0dks/whiteboard#45]
Would you consider supporting PDF embeds, dragged-and-dropped into the whiteboard just like images? Only the first page of the PDF would be rendered, of course. Several commercial whiteboards offer this feature already, and I think it makes sense especially in an educational context.

Thank you for this fantastic piece of work.

**Comment by cracker0dks** [comment]
mmm we would probably need to add the [pdf.js](https://github.com/mozilla/pdf.js/) lib. Is this really a feature that would be used often so it's worth to implement? 
I'll wait for others to comment on this one first :)

**Comment by yrammos** [comment]
Thanks for your consideration. PDFs are ubiquitous and image formats much less common in academic contexts. Converting to PNG is an option, but cumbersome and several clicks away, so I’d end up grabbing a screenshot of the page, producing an unnecessarily large PNG that eats up resources.

**Comment by yrammos** [comment]
(By the way, server-side imagemagick might also be an option, though no idea which one would be simpler.)

**Comment by semencha** [comment]
Collaboration with pdf is needed, now we will convert everything into images and place it on canvas. If it’s possible to paint on top of pdf, it will be great.

Regards, Ivan Semencha

**Comment by cracker0dks** [comment]
added this function with the last commit. I used pdfjs because you don't need install imagemagick on the serverside and the upload is a lot smaller with one image compaired to the hole pdf.
Please check it if it fits your needs and give feedback.
greetings

**Comment by yrammos** [comment]
@cracker0dks works as promised, and then some. Thank you!
