### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#47]
Hi,

I experience quite a performance breakdown in the middle of the day, when lots of whiteboards have been used. My idea was to use a nginx load balancer to split the requests up to multiple instances/servers. I open up two whiteboards (on 8080 and 8081) and use the config below. Then the whiteboards does not work any more. Strange thing ist, that a few lines get drawed, but very randomly. The cursor of other participants is not visible any more.

```
upstream backendwhiteboard {
	hash $request_uri;
	server localhost:8080;
        server localhost:8081;
    }
	
server {
        server_name MYDOMAIN.XYZ;

        location / {
		proxy_pass http://backendwhiteboard;
	}
}
```

Do you have an idea how to get a load balancer working?

Regards

**Comment by cracker0dks** [comment]
you need to make sure that one whiteboard id will end up on always the same server. I think the with your solution the request from client 1 can end up on a different server than client 2 so they will not see each other or what the draw. You need to bind the server to the whiteboardid. Maybe this helps: https://serverfault.com/questions/489388/how-can-i-setup-an-nginx-load-balancer-using-a-get-parameter

**Comment by tna76874** [comment]
thanks, I'll try again. If I find a config that works, I will report here.

**Comment by cracker0dks** [comment]
Do you know why you had a breakdown? Was it CPU or RAM limitied?

**Comment by tna76874** [comment]
the board became very very "laggy". I have 60GB of RAM on my machine that was not on the limit. CPU was also not at the limit. But I will check again next week if the performance get worse.

**Comment by cracker0dks** [comment]
maybe you encounter the 1gb ram limit from node? https://stackoverflow.com/questions/7193959/memory-limit-in-node-js-and-chrome-v8

**Comment by tna76874** [comment]
this may be an issue. Would it be possible to increase the memory limit of node.js with an docker environment variable?

**Comment by cracker0dks** [comment]
you should be able to change that out of the box already: https://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory/48895989#48895989

**Comment by tna76874** [comment]
I put it now in my .bashrc. But somehow that seems strange to me. Does that really increase the memory limit of my docker-container?

I found this posting here, what do you think of it?

https://github.com/npm/npm/issues/12238#issuecomment-314232479

**Comment by cracker0dks** [comment]
no I think you need to put the env var inside the docker container like this:
`docker run -d -p 8080:8080 -e NODE_OPTIONS='--max_old_space_size=4096' rofl256/whiteboard`

**Comment by tna76874** [comment]
thanks,
I'm starting my docker-compose with this, and gonna give it a try. I report if performance will be better next week :)

```
version: '3.1'
services:
  whiteboard:
    image: rofl256/whiteboard
    restart: always
    ports:
      - 8080:8080/tcp
    environment:
      - accesstoken=mysupersecretkey
      - NODE_OPTIONS='--max_old_space_size=4096'
```

**Comment by FloChehab** [comment]
Hi,
Just wanted to let you know that I am currently working on some tweaks to increase the performances of this project (by changing some behaviors to reduce the number of messages and small websockets optimization).
I'll most likely open a PR tomorrow or Friday.

**Comment by tna76874** [comment]
I did not get the nginx load balancing running - but maybe things change anyways if the read-only function will be implemented (thanks for that!).

Is there any other possibility to effectively scale the whiteboard system for a very big usergroup. Video-Conferencing software distributes the conferences on multiple videobriges (e.g. jitsi / BigBlueButton). This may be an overkill, but I think it would be awesome If there was a setting to distribute whiteboard ID's to an array of servers:

localhost, accesstoken
server1.xyz, accesstoken2
server2.xyz,None

**Comment by tna76874** [comment]
seems to be much better now with the optimizations in #50

**Comment by tna76874** [comment]
I'm afraid I need to pop up here again. With the new config file things might be better sometimes. But in the last days it gets VERY annoying that the whiteboard randomly "freezes". Refreshing the page (F5) does not solve the problem most of the times.

Can you please tell, if there is already a possibility to fix this via the new config file? Or is there any other possibility to stabilize the performance?

Regards :)

**Comment by cracker0dks** [comment]
mmm might me a memory leak, can you get the amount of ram used by the docker if the lag starts ?
