### ISSUE TITLE
Straight lines with pen tool

### ISSUE THREAD

**Issue by yrammos** [cracker0dks/whiteboard#48]
@cracker0dks As a fan of the Shift-key modifiers that apply to the line and rectangle tools, may I suggest extending the feature to the pencil tool, also? The sequence of events would be this: 

* select pen tool
* locate point of origin (A) on the canvas
* press Shift
* roll the pen around the canvas
* remove the pen from the canvas at point (B)

Result: a straight line between points (A) and (B).

Obviously, this assumes that a thin dotted guideline would continuously connect (A) and the cursor while the cursor is being moved, providing feedback before the line is actually drawn.

Hope this makes sense. Thanks!

**Comment by yrammos** [comment]
Update: Am overcomplicating this, sorry. What I'm suggesting is effectively using the continuous `Shift` modifier to toggle between Pen and Line tools, when either is selected.

**Comment by cracker0dks** [comment]
create idea, done: https://github.com/cracker0dks/whiteboard/commit/ea0e9f84527f108ac7d886b11a7b37afd0c09448
greetings

**Comment by yrammos** [comment]
Thank you so much, @cracker0dks 

I managed to run into a quirk: If you release the Shift key prematurely, before the pen itself, then no line is drawn. This is all right. Next time the technique is used, though, the straight line is drawn between the wrong points. Are you able to reproduce this?

**Comment by cracker0dks** [comment]
yes, fixed that, should work better now.

**Comment by yrammos** [comment]
Thanks! Now the line slope changes in 45-degree increments only but, in fact, this is more convenient than my original suggestion! Case closed, as far as I'm concerned.

**Comment by cracker0dks** [comment]
yes, because lineTool + shift will only draw straight lines and that is the case her :)
