### ISSUE TITLE
Crach when IOS Ipad use the Whithboard

### ISSUE THREAD

**Issue by JeromeD84** [cracker0dks/whiteboard#49]
Hi,

Thx for the WhiteBoard, it's wonderfull.

All works, expeted i have a big problem. When i use my IPAD en IOS 13.3.1, then the deamon server chash just after the first draw line by my Ipad.

Error :
-------------------------------------------------------------
/scripts/server-backend.js:235
                smallestScreenResolutions[whiteboardId][socket.id] = content["windowWidthHeight"] || { w: 10000, h: 10000 };
                                                                   ^

TypeError: Cannot set property 'xeOdrrSY2nSDlv7dAABl' of undefined
    at Socket.<anonymous> (/scripts/server-backend.js:235:68)
    at Socket.emit (events.js:315:20)
    at /node_modules/socket.io/lib/socket.js:513:12
-------------------------------------------------------------

Can you help me ?

Regards, Jerome

**Comment by cracker0dks** [comment]
Dont know why no whiteboardId was set in your case, but server should not crash anymore.

**Comment by JeromeD84** [comment]
Sorry, i forget to answer. 

Now is good and all functions work with my Ipad.

Thx
