### ISSUE TITLE
nginx "pretty url" server block

### ISSUE THREAD

**Issue by kmorton1988** [cracker0dks/whiteboard#5]
Wanna work on modifying the nginx location block so that you can go to 

iporurl.com/boardid

Will input/edit as I try.

**Comment by kmorton1988** [comment]
Closest I've gotten so far: (forgive my overal ignorance with nginx, learning as I go here)

``` 
upstream whiteboard {
        server 127.0.0.1:8080;
}

server {
        listen server.fqdn.tld:80 ; #hosted on a subdomain. 

        root /var/www/html;

        index index.html index.htm index.php;

        server_name server.fqdn.tld;

        location / {
                proxy_set_header HOST $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
                proxy_pass http://whiteboard$uri; 
        }
}
```

This ends up passing ALL requests through as "server.fqdn.tld?whiteboardid=" with nothing else attached. I have to do more digging into nginx to try and make this work better. Will continue when I can, but I'm loving the server app so far.

**Comment by cracker0dks** [comment]
like the idea but can't really help you with nginx.

**Comment by kmorton1988** [comment]
That’s fine! I guess it was more for me to track progress and results. I imagine others may want to see this happen too. If there’s a better place than the “issues” area, let me know.

**Comment by spiral6** [comment]
@kmorton1988 I have it running on a NGINX server like so:
```
location /whiteboard/ {
        proxy_set_header HOST $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_pass http://192.168.1.104:8080/;
    }
```

Where that IP address is the Node app's IP address and port. Works just fine. If you want it to run on the root location, just replace that /whiteboard with a regular /. If you want it to run a subdomain, set the `server_name` to `whiteboard.example.com` .

**Comment by spiral6** [comment]
If you want to have the arguments as a /, use the NGINX rewrite module to do so.
