### ISSUE TITLE
Exprt PNG doesn't print the CR (line return) caracter

### ISSUE THREAD

**Issue by JeromeD84** [cracker0dks/whiteboard#54]
Hi,

When i use the function to export PNG Format, i receive an PNG image without the returns lines.

Original :
![Original](https://user-images.githubusercontent.com/64906477/81653528-2dc0a980-9435-11ea-8275-bcba53af1246.png)

The PNG :
![PNG Format](https://user-images.githubusercontent.com/64906477/81653561-39ac6b80-9435-11ea-9e80-84155acbc9b8.png)

Can you help me ?

Regards

**Comment by cracker0dks** [comment]
thanks for the report, should work now: https://github.com/cracker0dks/whiteboard/commit/1c664a810e493c5f016792d0d4eb11343841ac55

**Comment by JeromeD84** [comment]
Thx for your action, but it doesn't work.

Whiteboard Version :
![image](https://user-images.githubusercontent.com/64906477/81742324-3ac6b280-94a0-11ea-8dcf-5c78e3d3c80e.png)

PNG Version :
![image](https://user-images.githubusercontent.com/64906477/81742372-4b772880-94a0-11ea-976d-236a8b0755fd.png)

I can see two problems.
   - The first is between the line "Number 2" and the line Number 3", There is a string : "<BR>" in the PNG
   - The second problem is with the line 1 and the line 2. The PNG image show them in the same line but with Whiteboard, they are not.

Regards

**Comment by cracker0dks** [comment]
can you tell me the browser you have this problem with? Linebreaks in editable div is maybe handeled in some diffrent ways in your browser. Firefox and chrome should work.

**Comment by JeromeD84** [comment]
Hi,

I use my PC with Chrome Version 81.0.4044.138

Regards

**Comment by cracker0dks** [comment]
ah I see, you have no line breaks... changed it again, please give it a try: https://github.com/cracker0dks/whiteboard/commit/f49542adea03fcb86975dcf42114d6d77622ffb8

**Comment by JeromeD84** [comment]
Hi,

It works now. Thank you.
You can close this topic.

Regards
