### ISSUE TITLE
autoscale inserted image

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#55]
Sometimes it gives very nasty error messages when you try to insert an image or even a screenshot  with the wrong filesize. Is there a way to auto downscale the image, if it is to big? or set the maximum uploadsize of images?

Regards

**Comment by cracker0dks** [comment]
I don't saw this error ever. Are you sure this is not a nginx limit? What is the error msg you get?

**Comment by tna76874** [comment]
yep - indeed some reverse proxy error. this config fixed it:
`client_max_body_size 5M;`
