### ISSUE TITLE
Access denied! Wrong accessToken

### ISSUE THREAD

**Issue by JeromeD84** [cracker0dks/whiteboard#56]
Hi,

In the last versionof Withboard, when an user try to connect with a bad AccessToken (URL Get argument) then he received the message "Access denied! Wrong accessToken!" (Windows Alert).

But now, with the last version of Withboard, if you use a bad AccessToken, you dont't receive a message. The security is still good, because, the user can't use the Whiteboard, but he doesn't understand.

./usr/js/main.js :
-----------------

>         let accessDenied = false;
>         signaling_socket.on("wrongAccessToken", function () {
>             if (!accessDenied) {
>                 accessDenied = true;
>                 showBasicAlert("Access denied! Wrong accessToken!");
>             }

Browser version : Chrome PC last version
Whiteboard ; Last version

**Comment by cracker0dks** [comment]
thanks for the report, should be fixed: https://github.com/cracker0dks/whiteboard/commit/eef7c52c7ee516a3afea192389723bfdef739e7f

**Comment by JeromeD84** [comment]
Perfect, it works now.

Thank you
