### ISSUE TITLE
image download configurations

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#57]
Hi chaps,

For me it would be handy to set the downloaded image of the whiteboard to jpg instead to png, including the background. Would it be possible to implement these two settings in the config file?

Regards

**Comment by cracker0dks** [comment]
Added this as an option with this commit: https://github.com/cracker0dks/whiteboard/commit/d804f56152e853f38a371fbd810b26159c701f42 
check out the default config to see where and how it's defined.
greetings

**Comment by tna76874** [comment]
cool, thanks :)

is it possible to include the grid in the jpeg as well, also as a config parameter maybe?

**Comment by tna76874** [comment]
I testet the new feature - now it is possible to download as jpeg - thanks.

But if I set to jpeg now, it is not possible to UPLOAD any image to the whiteboard ....

**Comment by cracker0dks** [comment]
fixed the image upload bug and added an option to draw the grid to the download image. Thanks for the report.
