### ISSUE TITLE
"Digital Wellbeing"

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#58]
Can you please add a config to set the color of the background to another color. Sometimes it is very exhausting to look at the bright white the whole day :)

**Comment by cracker0dks** [comment]
I added an option to define the background grid image. The best way is to change the background in the Image and mount it into the container. If you want, you can send the changed image (or make a PR) to add it to the main project for everyone to use :)

**Comment by tna76874** [comment]
somehow the background gets changed if I edit the image file. Is there any possiblity to use grid and background color independent? A template for the grid + a hex color code for the background?

**Comment by cracker0dks** [comment]
what do you mean by: "somehow the background gets changed if I edit the image file. " ? I thought you want to change the background? The best way is to take one of the given backgrounds into photoshop/gimp (the have a transparent background) and add a background layer with the color you want. 
If you give me the hex code I will do that, but to add a function and config seems to be overkill. If we have some different colors to choose from this should be fine.

**Comment by tna76874** [comment]
The background-file is shown different in the whiteboard as in gimp. But I think this is somehow a feature of the whiteboard. For now I have a few backgrounds - but when saving them as image the whole thing looks completely different. For me it looks linke the whole background gets lightend with the whiteboard. It is kind of confusing

**Comment by cracker0dks** [comment]
can you add an example here please?

**Comment by tna76874** [comment]
the upper image is the background/grid when using the whiteboard. In the bottom is the saved image via the button. If using another background the effect is also much stronger.

![demo](https://user-images.githubusercontent.com/47271687/83294087-fe5bbc00-a1ec-11ea-9648-605a54361257.jpg)

**Comment by cracker0dks** [comment]
I think the problem occurs if you draw a transparent png to a canvas (or transparent color in the png), it only draws the color, not the transparent part. Maybe I find a way around that.

**Comment by tna76874** [comment]
> I think the problem occurs if you draw a transparent png to a canvas (or transparent color in the png), it only draws the color, not the transparent part. Maybe I find a way around that.

thank you :)

**Comment by cracker0dks** [comment]
background should now be transparent as well, give it a try :)

**Comment by tna76874** [comment]
Thanks, I'm gonna test it. If I find some good choice of backgrounds/grids I'll "PR-it" :)
