### ISSUE TITLE
When integrated in Nextcloud, download buttons don't work.

### ISSUE THREAD

**Issue by poVoq** [cracker0dks/whiteboard#6]
I get a "Content Security Policy" error in Firefox when trying to download the image or json file.

I guess this is a security feature of the browser to prevent download popups from an iframe? Maybe there could be a alternative pop-up similar to the one for sharing and image upload that would just give a download URL to manually download it?

**Comment by cracker0dks** [comment]
thanks for the report.
Seems to be a "specification issue": https://bugzilla.mozilla.org/show_bug.cgi?id=1365502

Two problems with the solution of you:
1. We can't show download links at this popups (javascript alerts don't allow html). We would have to write own popups
2. Even then, we are still in the IFrame and it would be blocked like before. 

I think we need to send the Base64 and JSON to the server and use a direkt download link... but I will have to take a closer look.

As workaroundyou could check the checkbox at Nextcloud -> External Sites ->(Select whiteboard) -> Redirect. Then the whiteboard opens as own page.

**Comment by poVoq** [comment]
The copy to clipboard share URL seems to work though. Maybe as an option have that for download links as well?

**Comment by cracker0dks** [comment]
yes, we can copy links to the clipboard, but this is data-url so it can be massiv (as huge as the img). This would also not trigger the download... so you would have to open a new tab->past.
The problem with the server solution i meantioned: you have to upload the img/json first before you can download... not very efficient.

**Comment by cracker0dks** [comment]
Found a way around by open a extra tap for a milliseconds. Should be fixed: https://github.com/cracker0dks/whiteboard/commit/b839fd66fa11d094353426751be4327734549c84
Can you confirm and close please?

**Comment by poVoq** [comment]
Great, works fine now :)
