### ISSUE TITLE
Is there a way to integrate this to react based project ?

### ISSUE THREAD

**Issue by simo97** [cracker0dks/whiteboard#60]
Hi 

i am working on a online teaching tool and i want to know if there a guide on integrating whiteboard with react. As it looks like there is a lot of dependancies on Jquery. 

thanks

**Comment by cracker0dks** [comment]
hey, I never used react yet so don't know. Have you consider some css changes and a borderless iframe? I think https://meetzi.de/ did it that way. Think this would be easy for update as well. 
greetings

**Comment by simo97** [comment]
Css changes aren't the main important things in the process actually.  Anyway i've been able to do it and it works well with my react project. It didn't need much changes, the main thing is to know where to call `main()` function as it will trigger the whiteboard display and also use JQuery binding for React.

Anyway when possible i will write an article on that process and put it on my blog: blog.adonissimo.com
