### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by praful67** [cracker0dks/whiteboard#63]
Hello, I just run npm install and then after node scripts/server.js but its error
`{ backend:
   { accessToken: '',
     enableWebdav: false,
     performance: { whiteboardInfoBroadcastFreq: 1 } },
  frontend:
   { onWhiteboardLoad: { setReadOnly: false, displayInfo: false },
     showSmallestScreenIndicator: true,
     imageDownloadFormat: 'png',
     drawBackgroundGrid: false,
     backgroundGridImage: 'bg_grid.png',
     performance:
      { refreshInfoFreq: 5,
        pointerEventsThrottling:
         [ { fromUserCount: 0, minDistDelta: 1, maxFreq: 30 },
           { fromUserCount: 10, minDistDelta: 5, maxFreq: 10 } ] } } }
C:\Users\praful\Desktop\Projects\whiteboard-master\scripts\services\ReadOnlyBackendService.js:9
    #idToReadOnlyId = new Map();
    ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
`

**Comment by cracker0dks** [comment]
Please follow: https://github.com/cracker0dks/whiteboard#without-docker
Do you still get this error when you try it that way?

**Comment by praful67** [comment]
> Please follow: https://github.com/cracker0dks/whiteboard#without-docker
> Do you still get this error when you try it that way?

First I typed: npm install,  where I didn't see any node_modules folder so I run this command
Second I simply run :  npm run start:dev 

then i got this error later 
i run : npm ci, where it deleted the node_modules folder that was created by me. so i have to again run the command : npm install,
then i run : npm run start:dev  and again i got same error.

**Comment by cracker0dks** [comment]
Are you sure you running node 12 or heigher? Or maybe @FloChehab know what this could mean? :)

**Comment by FloChehab** [comment]
> Are you sure you running node 12 or heigher? Or maybe @FloChehab know what this could mean? :)

Hi, I agree with you @cracker0dks, @praful67 it looks like you are running with a node version <12. You should be able to install node 12 from here https://nodejs.org/en/download/ or your preferred location.

**Comment by praful67** [comment]
Thanks for the reply, I am installing version 12 now and there was one more issue, I cant scribble in the mobile browser. Any idea?
