### ISSUE TITLE
Apache reverse proxy failing with uploads

### ISSUE THREAD

**Issue by yrammos** [cracker0dks/whiteboard#65]
Installed on Ubuntu 18.04 with Node 12.18.2 and Apache 2.4.29. After some tinkering I managed to have the socket.io connection established with no errors whatsoever.

Unfortunately, POST requests to `/api/upload` fail consistently with a 502 Proxy Error. The following inspector dump confirms that the POST request is indeed sent to the server, but a response is never received back:

```
Summary
URL: https://staging.tekhn.ee/api/upload
Status: 502 Proxy Error
Source: Network
Address: 172.104.133.116:443
Initiator: 
main-147ecf3ffff378730f70.js:25:78928


Request
POST /api/upload HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Accept-Language: en-us
Accept-Encoding: gzip, deflate, br
Host: staging.tekhn.ee
Origin: https://staging.tekhn.ee
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Connection: keep-alive
Referer: https://staging.tekhn.ee/?whiteboardid=myNewWhiteboard
Content-Length: 77980
Cookie: io=qhm6SXDuZyy85JGcAAAw
X-Requested-With: XMLHttpRequest

Response
HTTP/1.1 502 Proxy Error
Content-Type: text/html; charset=iso-8859-1
Date: Fri, 03 Jul 2020 09:39:27 GMT
Keep-Alive: timeout=5, max=100
Content-Length: 424
Connection: Keep-Alive
Server: Apache/2.4.29 (Ubuntu)
Strict-Transport-Security: max-age=15552000; includeSubDomains
```

I've tried a slew of alleged solutions (timeouts, keepalive settings, relaxing header checks, …) to no avail.

The issue is not manifest browsing locally from localhost. This is clearly a reverse proxy issue.

Having spent half a day on this, I'd be most grateful for any thoughts.

Apache settings follow:

```
<VirtualHost *:443>
        SSLEngine On

        ServerName my.domain.tld
        ServerAdmin my@email.tld

        ProxyPreserveHost On
        ProxyRequests off
        ProxyVia on
        ProxyTimeout 60

        RewriteEngine On
        RewriteCond %{REQUEST_URI}  ^/ws-api               [NC]
        RewriteCond %{QUERY_STRING} transport=websocket    [NC]
        RewriteRule /(.*)           ws://localhost:8080/$1 [P,L]

        ProxyPass        /ws-api ws://localhost:8080/ws-api
        ProxyPassReverse /ws-api ws://localhost:8080/ws-api

        <Location />
                ProxyPass               http://localhost:8080/
                ProxyPassReverse        http://localhost:8080/
        </Location>

        SSLProxyCheckPeerCN on
        SSLProxyCheckPeerName on
        SSLProxyCheckPeerExpire on
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"

        LogLevel warn
        Use LoginLoggers

        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/domain.tld/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/domain.tld/privkey.pem
</VirtualHost>
```

**Comment by cracker0dks** [comment]
Don't use apache so can't really help on the config part there, but /loadwhiteboard is working so this should work as well. Are you sure that the server is allowed to write files to "/uploads" maybe this is just a permission problem? Do you get errors on the node (whiteboard) server?

**Comment by yrammos** [comment]
@cracker0dks thanks for the quick reply. Where is `/uploads` supposed to be located? Clearly it should be under `${rootUrl}/` — is this the root path of the repo (at the same level as `package.json`, for instance)? I fail to see it anywhere, which makes me think that this might be a permissions problem indeed.

**Comment by yrammos** [comment]
UPDATE: Permissions issue, indeed. Duh… not my customarily lucid self today :) Thanks, @cracker0dks
