### ISSUE TITLE
socket connections persist after leaving the whiteboard

### ISSUE THREAD

**Issue by simo97** [cracker0dks/whiteboard#66]
Hi, i've implemented whiteboard in my projet but i am facing an unexplicable issue now. 

When i connect to a whiteboard instance with an id it shows *"1 user connected"* when someone else connect it shows *"2 user connected"* but if the first user close the whiteboard and reconnect to the same whiteboard it will show *"3 user connected"*

i don't have any idea of why it's doing that. do you have any idea of where i can look to fix this ?

Here is the code.
```js
socket.on("joinWhiteboard", function (content) {
        content = escapeAllContentStrings(content);
        if (accessToken === "" || accessToken == content["at"]) {
            whiteboardId = content["wid"];
            roomName = content["course"];
            currentConnection[socket.id]={"whiteboardId":whiteboardId};
            socket.emit("whiteboardConfig", {
                common: confog.frontend,
                whiteboardSpecific: {
                    correspondingReadOnlyWid: ReadOnlyBackendService.getReadOnlyId(
                        whiteboardId
                    ),
                    isReadOnly: ReadOnlyBackendService.isReadOnly(whiteboardId),
                },
                users:{users:allRoomAttr[roomName]["users"]},
                courseInfo:{info:allRoomAttr[roomName]},
            });

            socket.join(whiteboardId); //Joins room name=wid
            const screenResolution = content["windowWidthHeight"];
            WhiteboardInfoBackendService.join(socket.id, whiteboardId, screenResolution);
        } else {
            socket.emit("wrongAccessToken", true);
        }
    });
```
it's basically the same than the original one.

Best Regards

**Comment by cracker0dks** [comment]
can't reproduce that on the current master. Take a look at /scripts/services/WhiteboardInfoBackendService.js line: 192 and below. You could add a debug console log there and check if it's called or why not.

**Comment by simo97** [comment]
I think it's good now. I was creating many socket on the client side. I was doing it bad. thank for the support i will close this issue now
