### ISSUE TITLE
Optimize co-working on different screen sizes

### ISSUE THREAD

**Issue by bpcurse** [cracker0dks/whiteboard#7]
If you use whiteboard on different screen sizes, let's say large desktop and tablet. The one using the tablet won't see anything drawn outside the tablet screen limits.
The problem is, there is no way for the user with the smaller screen to know that there is any information beyond the screen limits.

I was thinking about some possible ways to deal with this and came to these ideas:

- Show the screen limits of the smallest screen on all larger screens (e.g. dotted grey lines)
- Show small arrows to the right or bottom on the smaller screens to indicate that there is more hidden information and
   - add zoom functionality and / or
   - add scroll functionality

**Comment by cracker0dks** [comment]
An other option could be a minimap on the small screens. Don't know the best way... I will talk to an UX designer within the  next days, maybe he knows a good solution...

**Comment by cracker0dks** [comment]
After some thoughts and talks I finally added an indicator to show the smallest screen resolution participating: https://github.com/cracker0dks/whiteboard/commit/31f0b7349ec8200b05583bfb2d966ffee434a88c
Tell me what you think :)

PS: you can disable it with a [start parameters](https://github.com/cracker0dks/whiteboard#all-run-parameters-also-docker) if you don't like it

**Comment by bpcurse** [comment]
I have only tested it once with a desktop screen and a mobile phone, but it seems to work very good :+1: 
Will try to test it with more than 2 devices in the next days.

Thank you for your efforts!
