### ISSUE TITLE
bug: not possible to draw points

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#72]
Hi,
drawing a simple point by tipping on the whiteboard is not possible. I always have to make some kind of bubble to draw a point. Is there a way to fix this?
Regards

**Comment by cracker0dks** [comment]
hey,
thanks for the report. Should be fixed now. https://github.com/cracker0dks/whiteboard/commit/b0be5ff523334cd34fb08eef87de6eca5ebde81d
greetings

**Comment by tna76874** [comment]
indeed - thanks a lot !
