### ISSUE TITLE
Apache reverse proxy settings?

### ISSUE THREAD

**Issue by muranava** [cracker0dks/whiteboard#74]
Hi
What are the reverse proxy settings for Apache2?
thanks

**Comment by cracker0dks** [comment]
Dont have one but you can try something like this:

````
<VirtualHost example.org:443>
...
# Proxy /whiteboard/ to whiteboard container
ProxyPass "/whiteboard/" "http://127.0.0.1:8080/"
ProxyPassReverse "/whiteboard/" "http://127.0.0.1:8080/"
...
</VirtualHost>
````
please tell me if it works

**Comment by muranava** [comment]
sweet it is working thanks!

**Comment by muranava** [comment]
not sure if error related to this but after getting whiteboard working with external sites on nextcloud with these reverse proxy settings and sharing a whiteboard it knocked off my nextcloud server?

**Comment by cracker0dks** [comment]
do you find something in the logs ? I don't think it is possible for an external site to shut down the nextcloud server. (Would be a major bug).

**Comment by muranava** [comment]
got the following error:
`Error: Use  of undefined constant integer - assumed 'integer' (this will throw an  Error in a future version of PHP) at  /var/www/nextcloud/apps/whiteboard/lib/Db/User.php#39
`

**Comment by cracker0dks** [comment]
can you include other external sites into your nextcloud?

**Comment by muranava** [comment]
yes just tried  another exiternal site, it works okay; 
the issue with the whiteboard occurs when i share a whiteboard?

**Comment by cracker0dks** [comment]
I don't have a problem with that. External sites is just an iframe inside nextcloud afaik, so don't know how it could be possible for a exterlan site to crash the nextcloud. I think you need to open up a nextcloud issue as well: https://github.com/nextcloud/server/issues

**Comment by muranava** [comment]
ok thx; i think it is something to do with reverse proxy settings and modsecurity?

**Comment by cracker0dks** [comment]
glad you found it 👍
