### ISSUE TITLE
Mobile UI support

### ISSUE THREAD

**Issue by IgorKhomenko** [cracker0dks/whiteboard#75]
Hi everyone, 

Is there any plans to make the app more mobile users friendly?

As for now, the tool bar is too small, making it bigger will improve the UX a lot

![IMG_3782](https://user-images.githubusercontent.com/70977170/100593290-e8949400-3300-11eb-8f85-85e172bc0687.PNG)

Thank  you

**Comment by cracker0dks** [comment]
Its not perfect, but I added some lines to make it a bit more responsive. Need to work on that a bit more but buttons should be bigger now :)

**Comment by IgorKhomenko** [comment]
Thnaks @cracker0dks !
is it automatically deployed to https://cloud13.de/testwhiteboard/ ?

**Comment by cracker0dks** [comment]
yes, at 2:00 EST, so you need to wait a bit.

**Comment by DaveLomber** [comment]
Ok cool

It looks much better 👍

I played a bit more with it, here are furter optimizations/ideas:

1) it will be good to be able to hide some controls via config, e.g pics does not work well on mobile or sharing button is not required

![image](https://user-images.githubusercontent.com/39332586/100702456-5cd74200-33aa-11eb-8f58-4dbcbd413c18.png)

2) 'thickness' control is hard to use - it's too small. It's better to do it at least 3x by width

**Comment by IgorKhomenko** [comment]
Ok cool
It looks much better 👍

I played a bit more with it, here are further optimizations/ideas:
1. it will be good to be able to hide some controls via config, e.g pics does not work well on mobile or sharing button is not required

![IMG_3791](https://user-images.githubusercontent.com/70977170/100713599-32db4b00-33bd-11eb-9445-b8b5e2d6636f.PNG)


2. 'thickness' control is hard to use - it's too small. It's better to do it at least 3x by width

**Comment by cracker0dks** [comment]
should be better now. If not, please open a new issue
