### ISSUE TITLE
Add webdav support for directly saving to Nextcloud?

### ISSUE THREAD

**Issue by e-alfred** [cracker0dks/whiteboard#8]
Hello,

it would be awesome to be able to save the file crated using this app directly to Nextcloud using Webdav for example.

**Comment by e-alfred** [comment]
Hello,

it would be awesome to be able to save the file directly to Nextcloud using Webdav for example.

**Comment by cracker0dks** [comment]
Have to take  a look at webdav and a good solution. Definitely on the roadmap.

**Comment by e-alfred** [comment]
Since your app makes use of Node.js, maybe the webdav-fs module would make sense:

https://nextcloud.com/blog/using-webdav-fs-to-access-files-in-nextcloud/

**Comment by cracker0dks** [comment]
Yeah but maybe we don't need the way browser->sever->nextcloud and can go straight browser->nextcloud. https://www.npmjs.com/package/webdav-client has a "Web browser compatibility" but I need to invetigate both solutions first.

**Comment by e-alfred** [comment]
There is also this library if it can be more Nextcloud/Owncloud-centric:

https://www.npmjs.com/package/nextcloud-node-client

**Comment by cracker0dks** [comment]
Thought a bit more about this thing and I'm not sure it's a good idea to include this function into this project. The main problem: It's not done by just add a webdav lib. We would need a file explorer as well, and a modal function on top for the explorer. 
Then all the error handling (incorrect user config), and making sure you can't DOS things with it... 

On the other hand the user just could save/load files from his nextcloud synced folder instead and would be done.
You agree?

**Comment by e-alfred** [comment]
Sorry for the delay in responding here.

Maybe it would be okay to leave away a complete file explorer and instead only tell the user to create a folder on a Webdav server so they can provide the complete Webdav URL to that folder like `http://webdavserver.domain/remote.php/webdav/mywhiteboardfolder/`?

The advantage of saving directly to Nextcloud would be the absence of any dependency installed directly to the desktop system like the sync client or other software.

**Comment by cracker0dks** [comment]
Hey, 
finally added webdav save. It's alpha at the moment so you have to checkout the "webdav" branch.
To activate it do:
client: add "webdav=true" as get parameter to the url
server: add "--webdav=true" as start parameter

what do you think can be improved?

**Comment by e-alfred** [comment]
Awesome, I will test it out and report back to you!

**Comment by cracker0dks** [comment]
megred it into the master :)
