### ISSUE TITLE
Change devloper ip

### ISSUE THREAD

**Issue by sammrafi** [cracker0dks/whiteboard#80]
can I change the developer start to localhost to ip .....because of I'm getting some errors.and I'm using nginx proxy
also I'm getting Invalid Host header error in proxy
![Screenshot (48)](https://user-images.githubusercontent.com/31324166/102877224-9adaf980-4470-11eb-8f8e-c07bc93cae1f.png)

**Comment by cracker0dks** [comment]
Atm the client will always try to connect its websocket to the Host/ip given by the url. If you need to change that for development you need to make a change in the file /js/main.js line 49 and add a different host IP where "" ist present atm.

**Comment by sammrafi** [comment]
okay......I fixed this problem
