### ISSUE TITLE
Default tool

### ISSUE THREAD

**Issue by equintanillam** [cracker0dks/whiteboard#81]
Hello, thanks for your software, where I can modify the default tool, it is currently "Pen"
Thank you!

**Comment by cracker0dks** [comment]
not possible to change it through a config file, you could change in the code: https://github.com/cracker0dks/whiteboard/blob/1fcad771f140c35d1162361252a88e1498ab5b6b/src/js/whiteboard.js#L18
But might need changes at other lines as well (not tested this)

**Comment by equintanillam** [comment]
thanks!
