### ISSUE TITLE
Number of concurrent users

### ISSUE THREAD

**Issue by Mattegray** [cracker0dks/whiteboard#83]
Hi @cracker0dks!
I was able to integrate the whiteboard into my jitsi-meet installation.
I am curious how many concurrent users can this whiteboard support?
Can it support about 200 concurrent users, with about 8 users per whiteboard?
Thank you.

**Comment by cracker0dks** [comment]
I don't really have xp on how many users would work. I think you need to test it out with your own conditions (Hardware and stuff). Keep in mind that you could change some settings in you config under "performance": https://github.com/cracker0dks/whiteboard/blob/1fcad771f140c35d1162361252a88e1498ab5b6b/config.default.yml#L38
if it is not performing well.

**Comment by Jesusjbs** [comment]
Hi @Mattegray, can you explain how you integrated it?
Have you a repo where I can see the code or anything?
