### ISSUE TITLE
New PDFJs Import broken with webpack

### ISSUE THREAD

**Issue by cracker0dks** [cracker0dks/whiteboard#85]
I could not get the new version of Pdfjs running with webpack, tried a lot of stuff from here: https://github.com/mozilla/pdf.js/blob/master/examples/webpack/README.md and other things... and other sites. I'm not much into webpack so I don't see the problem :(
I ended up including the  static cdn file for pdfjs into the index.html, so it is running for now. Would be nice to get it into the build process again.
Maybe @FloChehab can help?

**Comment by FloChehab** [comment]
Hello @cracker0dks, sure, I'll try to look into it today.

**Comment by cracker0dks** [comment]
Thanks a lot :)
