### ISSUE TITLE
Whiteboard crashes Frequently

### ISSUE THREAD

**Issue by utkarshsystem** [cracker0dks/whiteboard#88]
Recently we started using the whiteboard but we lose our data because of frequent crashes. I see there is WebDAV data but I don't see any other way to take the backup of data every day using the command line.

**Comment by cracker0dks** [comment]
The whiteboard data will reset on server restart. Do you have any error msg for me when it crashes? 
I added the new API function yesterday :)
Added this part into the readme: https://github.com/cracker0dks/whiteboard/blob/master/README.md#rest-api
Hope this helps

**Comment by utkarshsystem** [comment]
Could you please implement the AWS s3 bucket and cron schedule for backup?

**Comment by cracker0dks** [comment]
I can not provide an  AWS s3 solution, but how about a file backup on the whiteboardserver  itself. (every minute or so) and loading in on server start? This way you would not lose the hole content of the whiteboard.

**Comment by utkarshsystem** [comment]
Sure that works i can define the path in properties file

**Comment by utkarshsystem** [comment]
How to take the current backup of data and reinstall the whiteboard so that we no longer lose the data?

**Comment by cracker0dks** [comment]
added the function so the whiteboard is saved to a file. Get the last code version, then you need to enable it through the config: set `enableFileDatabase` to `true` under "backend" https://github.com/cracker0dks/whiteboard/blob/1c23b8fc6ab60f3e93ae3ea88672dbe27b3b67b8/config.default.yml#L10 . The board  is saved to "savedBoards.json" every 10 sec if a change is detected... With docker you can mount it with `$(pwd)/savedBoards.json:/savedBoards.json` if you want to.

**Comment by utkarshsystem** [comment]
Does it save images too?

**Comment by cracker0dks** [comment]
Eidt your YML file according to https://github.com/cracker0dks/whiteboard/blob/1c23b8fc6ab60f3e93ae3ea88672dbe27b3b67b8/config.default.yml line 10. If you want the images saved as well you need to mount `$(pwd)/uploads:/public/uploads` (not tested but should work)

**Comment by cracker0dks** [comment]
you could do this yes, but it should be: `docker exec -it container_name /bin/sh`

**Comment by mehta-sumit** [comment]
why savedBoards.json file will empty after some day

**Comment by cracker0dks** [comment]
savedBoards.json is empty like no content at all?
