### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by utkarshsystem** [cracker0dks/whiteboard#89]
Recently we started using the whiteboard but I have to copy/paste every time the image from different locations. Is there any REST API image upload exists to paste on the whiteboard?

**Comment by cracker0dks** [comment]
Got a mail about this a few days ago so I added the new API 
Added this part into the readme: https://github.com/cracker0dks/whiteboard/blob/master/README.md#rest-api
The way to upload an image atm is to complicated, so I will add a better function soon. Right now you need 3 API requests to do this:

1- Get the readOnlyWhiteboard ID.
2. Upload the Image
3. Place the image to the board

Example for step 3.
```
$.ajax({
    type: "GET",
    url: "/api/drawToWhiteboard",
    data: {
        wid: "myNewWhiteboard",
        t: "addImgBG",
        draw: 0,
        url: "http://127.0.0.1:8080/uploads/15dbcff6-2ef5-45ae-ab7e-2f18e19d4160/15dbcff6-2ef5-45ae-ab7e-2f18e19d4160_1614597822311.png",
        d: [160, 164, -5, 173, 0],
    },
    success: function () { console.log("YEAH") },
    error: function (err) { console.error(err) },
});
```
