### ISSUE TITLE
Question: Open whiteboard with background image pre-populated?

### ISSUE THREAD

**Issue by Naam** [cracker0dks/whiteboard#91]
Hello,

I'm trying to host an instance of whiteboard. Everything works like a charm, but I'm failing to understand how to open a whiteboard without having users upload an image, scale it properly and set it to the background. This is a frequent task as this instance would be to collaborate on the same few things repeatedly.

For this, I have a parent page with a form, and depending on what button is clicked, it opens whiteboard with a different set of parameters through GET. However, I have not found the proper GET parameters in the documentation to initialize the whiteboard properly.

The possible solutions I see are:
- Create a whiteboard manually, save JSON and find a way to link the HTML button to loading whiteboard against that JSON. Is this doable?
- it seems that I could draw an image with the backend API. Is this feasible from an HTML form?
- Have a whiteboard saved on the server and duplicate on demand

I'm not sure how feasible those solutions are for me, and my web knowledge falls short here. Any help would be greatly appreciated.

Thanks!

**Comment by Naam** [comment]
Hi there, thank you very much for the fast reply. I appreciate it.

I will test this out but that seems perfect! Is there a way to prevent users from modifying the original whiteboard? I was thinking maybe set `enableFileDatabase = true` in the configuration then set the proper file corresponding to the original whiteboard to read-only on the server-side. But that sure seems hacky. I'm also not sure about the repercussions on error handling if whiteboard can't write to a file. 


Thank you again

**Comment by cracker0dks** [comment]
No problem :)
`enableFileDatabase = true` is a good idea so you don't need to redraw your templates after a server restart. 

We already have readOnly boards. Just draw on your template whiteboard and click on share. Use the readOnly WhiteboardID to copy from. Should be looking something like this: `https://cloud13.de/testwhiteboard/?whiteboardid=myTemplateWhiteboard&copyfromwid=21f37b4d-ddb8-47ce-bcd2-5193afd2e7eb`
