### ISSUE TITLE
How to publish website with github hosting

### ISSUE THREAD

**Issue by Ashwin-Paudel** [cracker0dks/whiteboard#92]
I am trying to publish the output files in the dist folder for github hosting
but when I look at the github website, I see that nothing works. 

**Here is link to website**
[https://ashwin-paudel.github.io/reimagined-octo-umbrella/?whiteboardid=myNewWhiteboard](https://ashwin-paudel.github.io/reimagined-octo-umbrella/?whiteboardid=myNewWhiteboard
)

Is there anyway I can host this website on github hosting?

**Comment by cracker0dks** [comment]
Websockets can not connect 
`Failed to load resource: the server responded with a status of 404 () https://ashwin-paudel.github.io/reimagined-octo-umbrella/ws-api/?EIO=3&transport=polling&t=NZ_BguY` I don't know github hosting but seems that subdirs are not passed through. Maybe you need to configure this somewhere? Do you get the log from the whiteboard server after startup? Maybe we get some more infos there.

**Comment by Ashwin-Paudel** [comment]
I do not know much about WebSockets. Could you perhaps tell me what files I should put in the ws-api folder? or where I can get the ws-api folder?

**Comment by cracker0dks** [comment]
No, the server should listening on this url already but might not get the request. Do you get the log of the nodejs server after startup?

**Comment by Ashwin-Paudel** [comment]
Where is the error log folder?

**Comment by cracker0dks** [comment]
there is no error log folder, you need to take a look at the console log of the server. Maybe github provides is, but I don't really know.

**Comment by Ashwin-Paudel** [comment]
ok, from the localhost or the github hosting?

**Comment by cracker0dks** [comment]
github hosting

**Comment by Ashwin-Paudel** [comment]
Here is image 
<img width="550" alt="Screen Shot 2021-04-23 at 10 58 07 AM" src="https://user-images.githubusercontent.com/62433766/115890382-e2739100-a422-11eb-86d4-2d02a9fe431c.png">

**Comment by cracker0dks** [comment]
thats the error log from the browser, we need it from the server side

**Comment by cracker0dks** [comment]
But it might not working at all! https://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages 
Seems that NodeJS is not supported, so you need a server with NodeJs support.

**Comment by Ashwin-Paudel** [comment]
Ok, also, where did you get the ws-api folder?
Was it provided by the hosting service you used?

**Comment by cracker0dks** [comment]
that is the subdir for the websocket connection. But the nodeJs server was not running so it could not connect.
Im running my own virtual server with docker. But something like https://www.heroku.com/ is working.

**Comment by Ashwin-Paudel** [comment]
So what hosting service do you use?

**Comment by cracker0dks** [comment]
Im useing a VPS from here https://contabo.com/en/vps/ the one for ~9€

**Comment by Ashwin-Paudel** [comment]
ok thanks, I'll look into that!

**Comment by cracker0dks** [comment]
no problem. With a VPS you need to setup docker, reverseproxy and so on all by your self, so you might just want something like heroku.

**Comment by cracker0dks** [comment]
If you only want to host the whiteboard, I would use heroku. If you want to host different things in parallel (nextcloud, email-server...) and full controll, I would use a VPS.

**Comment by Ashwin-Paudel** [comment]
ok thanks!

**Comment by Ashwin-Paudel** [comment]
https://whiteboard-learnish-com.herokuapp.com/?whiteboardid=learnish-whiteboard
I created it, Thanks!
