### ISSUE TITLE
Whiteboard is slow

### ISSUE THREAD

**Issue by utkarshsystem** [cracker0dks/whiteboard#95]
While running the whiteboard is slow sometimes and it takes too much time to load
![SlowWhiteboard](https://user-images.githubusercontent.com/1451615/117053022-70cef900-ace6-11eb-8984-6bb003721624.PNG)

**Comment by cracker0dks** [comment]
Have you changed performance settings at [config.default.yml](https://github.com/cracker0dks/whiteboard/blob/master/config.default.yml)? You can change them if you have to many users for your server setup.

**Comment by utkarshsystem** [comment]
What set you want us to change?

**Comment by cracker0dks** [comment]
don't know how many users  you have on your board(s). 
Maybe something like this: 
![image](https://user-images.githubusercontent.com/1816621/117189004-f84b6380-addd-11eb-9625-04f9138332ef.png)

**Comment by utkarshsystem** [comment]
but while loading if you see my chrome network page load it takes more time.

**Comment by cracker0dks** [comment]
Yes, I thought this is because your server can not handle the traffic so if you change this settings, every client will send/revive less and the respons time should go down.

**Comment by cracker0dks** [comment]
maybe also try the latest commit. I upgraded to the newest socket.io, maybe this helps a bit.

**Comment by gfafei** [comment]
> don't know how many users you have on your board(s).
> Maybe something like this:
> ![image](https://user-images.githubusercontent.com/1816621/117189004-f84b6380-addd-11eb-9625-04f9138332ef.png)

I found that when you draw line with pen, sendFuntion is not throttled, many draw action will send to server quickly, so the json file will grow fast, and the config won't help it.

I try to throttle pen drawing, and the line get discontinuous

**Comment by cracker0dks** [comment]
@gfafei All drawing date is send to the json file, if you slow down the send interval or not. Be sure you are on the latest patch so for each whiteboard there will be a separate json file.
